<!doctype html>
<html class="no-js" lang="en">

<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-134931760-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-134931760-1');
  </script>

  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Meet FreeCAD</title>
  <link rel="icon" type="image/x-icon" href="/favicon.ico" />
  <meta name="description" content="FreeCAD is a parametric three-dimensional editor that allows you to create three-dimensional models and drawings of their projections. 
 The current v...">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="../../css/main.css">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="../../js/vendors/jquery-3.3.1.min.js"><\/script>')</script>

  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <script>
       (adsbygoogle = window.adsbygoogle || []).push({
            google_ad_client: "ca-pub-6974184241884155",
            enable_page_level_ads: true
       });
  </script>
</head>

<body>
  <!--[if lte IE 9]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
  <![endif]-->
  <header class="page-header js-page-header">
    <a class="page-header-logo-container" href="https://weekly-geekly.github.io/index.html"></a>
    <div class="page-header-text">Geekly Articles each Day</div>
  </header>
  <nav class="page-headings-container js-page-headings-container"></nav>
  <div class="tools-bar js-tools-bar">
    <!-- <a href="../../search.html" title="Search">üîé</a> -->
    <a class="js-list-of-headings-button" data-state="closed" href="#" title="Headings">üìú</a>
    <a class="js-go-to-top-button" href="#" title="Go to Top">‚¨ÜÔ∏è</a>
    <a class="js-go-to-bottom-button" href="#" title="Go to Bottom">‚¨áÔ∏è</a>
  </div>
  <a href="http://bit.ly/donateToWeeklyGeekly" class="donate-btn">DONATE</a>
  <section class="page js-page"><h1>Meet FreeCAD</h1><div class="post__text post__text-html js-mediator-article">  <a href="https://sourceforge.net/apps/mediawiki/free-cad/index.php%3Ftitle%3DMain_Page">FreeCAD</a> is a parametric three-dimensional editor that allows you to create three-dimensional models and drawings of their projections. <br>  The current version of FreeCAD is 0.12, but you can also download the beta version 0.13 and try to compile it. <br><br>  FreeCAD supports several different document formats for both import and export, and also allows you to save "screenshots" (including in pdf format). <br><br>  Documentation for FreeCAD is quite abundant, but still not as complete as you would like.  Questions about using this product can be discussed on the <a href="https://sourceforge.net/apps/phpbb/free-cad/index.php">FreeCAD forum</a> . 
      <br>
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <ins class="adsbygoogle"
          style="display:block; text-align:center;"
          data-ad-layout="in-article"
          data-ad-format="fluid"
          data-ad-client="ca-pub-6974184241884155"
          data-ad-slot="8945601208"></ins>
        <script>
          (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
      <br>
    <a name="habracut"></a><br><img src="https://habrastorage.org/getpro/habr/post_images/17c/0aa/85d/17c0aa85d787607d73a498bfe6360952.png"><br><br>  For ease of drawing, FreeCAD has the ability to write scripts on python, and for small operations you can use the python console.  The console, however, is elementary: it has no command history. <br>  I will not rewrite the multi-volume FreeCAD user guide, but simply give an example of what can be done with it. <br><br>  But first, let me explain how to force FreeCAD to ‚Äúsee‚Äù your scripts.  Before each launch, FreeCAD looks at the contents of the system directories, as well as the ~ / .FreeCAD / Mod / directories.  He will use the scripts there in the future. <br><br>  The scripts in FreeCAD are divided into two categories: scripts called from the command line (to start, you must first load the module containing the python with the import command), as well as scripts launched from the GUI.  You can always reload the first with the reload command, but to reboot the second (if you made any changes to the sources), you will need to restart FreeCAD.  First consider the work with the first. <br><br><h2>  Draw the "wheel" </h2><br>  Create a sketch in the XY-plane and draw the profile of the ‚Äúhalf‚Äù of our wheel on it. <br><br><img src="https://habrastorage.org/getpro/habr/post_images/96e/8b8/ce8/96e8b8ce8bffe6038d3cdab3d69bd5ce.png"><br><br>  To do this, first "by eye" draw the basic shapes in the form of a broken line. <br>  Next, in the right places cut the chamfer (tool ¬´fillet¬ª).  And after that - we will place the bindings of points.  We will tie the starting points absolutely.  Parallel objects will be limited by parallelism, we will set the distances between the parts of the profile and the curvature radii. <br><br><img src="https://habrastorage.org/getpro/habr/post_images/44a/14b/4ee/44a14b4ee4eed824609b2896a3e7e260.png"><br><br>  Then we finish editing the sketch, select it in the list of objects (on the left) and click the "rotate the selected sketch" button.  We get the following wheel: <br><br><img src="https://habrastorage.org/getpro/habr/post_images/1e1/d69/718/1e1d69718e817ef1f335c21588a507cd.png"><br><br>  Now we will create notches in the ‚Äúdisk‚Äù.  To do this, we make another sketch in the XZ plane.  In it we make a cut of segments and arcs.  To make our hole exactly symmetrical about the center, let's bind to two invisible lines. <br><br><img src="http://img829.imageshack.us/img829/2327/k03w.png"><br><br>  Let's extend our sketch to 100 units (so that it will most certainly cross the wheel) and move it (Plasement.Position) 50 units along the Y axis: <br><br><img src="https://habrastorage.org/getpro/habr/post_images/4a3/e16/ba3/4a3e16ba3375b0df51279505cf322108.png"><br><br>  Now we need to "multiply" the resulting shape around the circumference, then to make cuts in the "wheel".  For "reproduction" we will write the NCopy.py script: <br><br><pre><code class="python hljs"><span class="hljs-keyword"><span class="hljs-keyword">import</span></span> FreeCAD, FreeCADGui, Part <span class="hljs-keyword"><span class="hljs-keyword">from</span></span> FreeCAD <span class="hljs-keyword"><span class="hljs-keyword">import</span></span> Base <span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">def</span></span></span><span class="hljs-function"> </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">CopyObj</span></span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">(obj)</span></span></span><span class="hljs-function">:</span></span> name = obj.Name shape = obj.Shape newshape = shape.copy() newobject = FreeCAD.ActiveDocument.addObject(<span class="hljs-string"><span class="hljs-string">"Part::Feature"</span></span>,name) newobject.Shape = newshape <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> newobject <span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">def</span></span></span><span class="hljs-function"> </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">copyCirc</span></span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">(C=Base.Vector</span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params"><span class="hljs-params">(</span></span></span><span class="hljs-number"><span class="hljs-function"><span class="hljs-params"><span class="hljs-params"><span class="hljs-number">0</span></span></span></span></span><span class="hljs-function"><span class="hljs-params"><span class="hljs-params">,</span></span></span><span class="hljs-number"><span class="hljs-function"><span class="hljs-params"><span class="hljs-params"><span class="hljs-number">0</span></span></span></span></span><span class="hljs-function"><span class="hljs-params"><span class="hljs-params">,</span></span></span><span class="hljs-number"><span class="hljs-function"><span class="hljs-params"><span class="hljs-params"><span class="hljs-number">0</span></span></span></span></span><span class="hljs-function"><span class="hljs-params"><span class="hljs-params">)</span></span></span></span><span class="hljs-function"><span class="hljs-params">, A=Base.Vector</span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params"><span class="hljs-params">(</span></span></span><span class="hljs-number"><span class="hljs-function"><span class="hljs-params"><span class="hljs-params"><span class="hljs-number">0</span></span></span></span></span><span class="hljs-function"><span class="hljs-params"><span class="hljs-params">,</span></span></span><span class="hljs-number"><span class="hljs-function"><span class="hljs-params"><span class="hljs-params"><span class="hljs-number">0</span></span></span></span></span><span class="hljs-function"><span class="hljs-params"><span class="hljs-params">,</span></span></span><span class="hljs-number"><span class="hljs-function"><span class="hljs-params"><span class="hljs-params"><span class="hljs-number">1</span></span></span></span></span><span class="hljs-function"><span class="hljs-params"><span class="hljs-params">)</span></span></span></span><span class="hljs-function"><span class="hljs-params">, Ang=</span></span><span class="hljs-number"><span class="hljs-function"><span class="hljs-params"><span class="hljs-number">90</span></span></span></span><span class="hljs-function"><span class="hljs-params">, N=</span></span><span class="hljs-number"><span class="hljs-function"><span class="hljs-params"><span class="hljs-number">4</span></span></span></span><span class="hljs-function"><span class="hljs-params">, rot=True, moveOriToGrp=False)</span></span></span><span class="hljs-function">:</span></span> Ang %= <span class="hljs-number"><span class="hljs-number">360</span></span> <span class="hljs-keyword"><span class="hljs-keyword">if</span></span> (N &gt; <span class="hljs-number"><span class="hljs-number">360</span></span>/Ang <span class="hljs-keyword"><span class="hljs-keyword">or</span></span> N == <span class="hljs-number"><span class="hljs-number">0</span></span>): N = int(<span class="hljs-number"><span class="hljs-number">360</span></span>/Ang) sel = FreeCADGui.Selection.getSelection() <span class="hljs-keyword"><span class="hljs-keyword">if</span></span> (<span class="hljs-keyword"><span class="hljs-keyword">not</span></span> sel): FreeCAD.Console.PrintError(<span class="hljs-string"><span class="hljs-string">"Error: you should select some objects"</span></span>) <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> <span class="hljs-keyword"><span class="hljs-keyword">None</span></span> doc = FreeCAD.activeDocument() grp = doc.addObject(<span class="hljs-string"><span class="hljs-string">"App::DocumentObjectGroup"</span></span>, <span class="hljs-string"><span class="hljs-string">"CircularCopy"</span></span>) <span class="hljs-keyword"><span class="hljs-keyword">for</span></span> Obj <span class="hljs-keyword"><span class="hljs-keyword">in</span></span> sel: A0 = Ang <span class="hljs-keyword"><span class="hljs-keyword">for</span></span> i <span class="hljs-keyword"><span class="hljs-keyword">in</span></span> range (<span class="hljs-number"><span class="hljs-number">1</span></span>, N): newobject = CopyObj(Obj) S = newobject.Shape S.rotate(C, A, A0) <span class="hljs-keyword"><span class="hljs-keyword">if</span></span> (<span class="hljs-keyword"><span class="hljs-keyword">not</span></span> rot): S.rotate(S.Placement.Base, A, -A0) grp.addObject(newobject) A0 += Ang <span class="hljs-keyword"><span class="hljs-keyword">if</span></span> (moveOriToGrp): grp.addObject(Obj) <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> grp</code> </pre> <br><br>  Save it in any subdirectory of ~ / .FreeCAD / Mod /. <br><br>  The CopyObj function has an auxiliary value (it will be useful to us later): this function simply creates a copy of this object. <br><br>  The copyCirc function has six arguments, all of which are assigned default values, so you can only call it by specifying arguments that have different values.  Her arguments are: <br><ul><li>  C - coordinates of the center of the circle on which the copying takes place; </li><li>  A is the normal to the plane of the circle; </li><li>  Ang is the angle between the copies; </li><li>  N - the number of copies (0 - if you need to place objects around the entire circle); </li><li>  rot - whether the object itself rotates when copying: if this parameter is False, the object will be distributed around the circle by parallel translation, and not by rotation; </li><li>  moveOriToGrp - whether to place the copied original in the general group of created objects. </li></ul><br>  We do not need the radius of the circle - we consider the distance from the object to the center of the circle.  Object [s] to copy ber [e | y] from selection.  If nothing is selected, simply issue the error text and terminate the function.  Next, we create the ‚ÄúCircularCopy‚Äù group as a function and begin to iterate over all the objects from the selection.  Each of them (N-1) is copied around the circle, and then placed in a group. <br><br>  Now let's estimate: the normal to the circle, along which it is necessary to ‚Äúmultiply‚Äù objects, has a value (0.1.0), make the angle between copies equal to 30 degrees, the center is located by default (at the origin), fill the entire circle.  So we need to give commands <br><br><pre> <code class="python hljs"><span class="hljs-keyword"><span class="hljs-keyword">import</span></span> NCopy NCopy.copyCirc(A=App.Vector(<span class="hljs-number"><span class="hljs-number">0</span></span>,<span class="hljs-number"><span class="hljs-number">1</span></span>,<span class="hljs-number"><span class="hljs-number">0</span></span>), N=<span class="hljs-number"><span class="hljs-number">0</span></span>, Ang=<span class="hljs-number"><span class="hljs-number">30</span></span>, moveOriToGrp=<span class="hljs-keyword"><span class="hljs-keyword">True</span></span>)</code> </pre><br><br>  Open the ‚ÄúCircularCopy‚Äù group that appears, select all the objects in it and execute their union, the ‚ÄúFusion‚Äù object will appear.  Now select our ‚Äúwheel‚Äù (‚ÄúRevolution‚Äù) and this union by pressing the Ctrl key, and select the ‚Äúintersection‚Äù operation.  As a result, cuts will appear in our ‚Äúwheel‚Äù: <br><br><img src="https://habrastorage.org/getpro/habr/post_images/2dd/ec8/372/2ddec8372012f2aa01347ffe21a52e87.png"><br><br>  And this is how the ‚Äúwheel‚Äù exported in pdf will look like: <br><img src="https://habrastorage.org/getpro/habr/post_images/fa9/5bd/832/fa95bd83254f37bdf6c061e7a13c43e7.png"><br><br><h2>  miscellanea </h2><br>  I will add some more functions for copying objects. <br><br>  Copying an object to a specified location (mv is the displacement vector, ax is the axis of rotation, rot is the angle of rotation): <br><br><pre> <code class="python hljs"><span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">def</span></span></span><span class="hljs-function"> </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">CopyObjAt</span></span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">(obj, mv=Base.Vector</span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params"><span class="hljs-params">(</span></span></span><span class="hljs-number"><span class="hljs-function"><span class="hljs-params"><span class="hljs-params"><span class="hljs-number">0</span></span></span></span></span><span class="hljs-function"><span class="hljs-params"><span class="hljs-params">,</span></span></span><span class="hljs-number"><span class="hljs-function"><span class="hljs-params"><span class="hljs-params"><span class="hljs-number">0</span></span></span></span></span><span class="hljs-function"><span class="hljs-params"><span class="hljs-params">,</span></span></span><span class="hljs-number"><span class="hljs-function"><span class="hljs-params"><span class="hljs-params"><span class="hljs-number">0</span></span></span></span></span><span class="hljs-function"><span class="hljs-params"><span class="hljs-params">)</span></span></span></span><span class="hljs-function"><span class="hljs-params">, axe=Base.Vector</span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params"><span class="hljs-params">(</span></span></span><span class="hljs-number"><span class="hljs-function"><span class="hljs-params"><span class="hljs-params"><span class="hljs-number">0</span></span></span></span></span><span class="hljs-function"><span class="hljs-params"><span class="hljs-params">,</span></span></span><span class="hljs-number"><span class="hljs-function"><span class="hljs-params"><span class="hljs-params"><span class="hljs-number">0</span></span></span></span></span><span class="hljs-function"><span class="hljs-params"><span class="hljs-params">,</span></span></span><span class="hljs-number"><span class="hljs-function"><span class="hljs-params"><span class="hljs-params"><span class="hljs-number">0</span></span></span></span></span><span class="hljs-function"><span class="hljs-params"><span class="hljs-params">)</span></span></span></span><span class="hljs-function"><span class="hljs-params">, rot=</span></span><span class="hljs-number"><span class="hljs-function"><span class="hljs-params"><span class="hljs-number">0</span></span></span></span><span class="hljs-function"><span class="hljs-params">)</span></span></span><span class="hljs-function">:</span></span> obj = CopyObj(obj) obj.Placement = FreeCAD.Placement(mv, axe, rot) <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> obj</code> </pre><br><br>  Copy N times to vector V: <br><br><pre> <code class="python hljs"><span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">def</span></span></span><span class="hljs-function"> </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">copyVec</span></span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">(N=</span></span><span class="hljs-number"><span class="hljs-function"><span class="hljs-params"><span class="hljs-number">2</span></span></span></span><span class="hljs-function"><span class="hljs-params">, V=Base.Vector</span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params"><span class="hljs-params">(</span></span></span><span class="hljs-number"><span class="hljs-function"><span class="hljs-params"><span class="hljs-params"><span class="hljs-number">0</span></span></span></span></span><span class="hljs-function"><span class="hljs-params"><span class="hljs-params">,</span></span></span><span class="hljs-number"><span class="hljs-function"><span class="hljs-params"><span class="hljs-params"><span class="hljs-number">0</span></span></span></span></span><span class="hljs-function"><span class="hljs-params"><span class="hljs-params">,</span></span></span><span class="hljs-number"><span class="hljs-function"><span class="hljs-params"><span class="hljs-params"><span class="hljs-number">1</span></span></span></span></span><span class="hljs-function"><span class="hljs-params"><span class="hljs-params">)</span></span></span></span><span class="hljs-function"><span class="hljs-params">, moveOriToGrp=False)</span></span></span><span class="hljs-function">:</span></span> sel = FreeCADGui.Selection.getSelection() <span class="hljs-keyword"><span class="hljs-keyword">if</span></span> sel: doc = FreeCAD.activeDocument() grp = doc.addObject(<span class="hljs-string"><span class="hljs-string">"App::DocumentObjectGroup"</span></span>, <span class="hljs-string"><span class="hljs-string">"VectorCopy"</span></span>) <span class="hljs-keyword"><span class="hljs-keyword">for</span></span> Obj <span class="hljs-keyword"><span class="hljs-keyword">in</span></span> sel: R0 = V <span class="hljs-keyword"><span class="hljs-keyword">for</span></span> i <span class="hljs-keyword"><span class="hljs-keyword">in</span></span> range (<span class="hljs-number"><span class="hljs-number">1</span></span>, N): newobject = CopyObj(Obj) newobject.Shape.translate(R0) grp.addObject(newobject) R0 += V <span class="hljs-keyword"><span class="hljs-keyword">if</span></span> (moveOriToGrp): grp.addObject(Obj) <span class="hljs-keyword"><span class="hljs-keyword">else</span></span>: FreeCAD.Console.PrintError(<span class="hljs-string"><span class="hljs-string">"Error: you should select some objects"</span></span>) <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> grp</code> </pre><br><br>  Copying N times along the path - B-spline: <br><br><pre> <code class="python hljs"><span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">def</span></span></span><span class="hljs-function"> </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">copyByTrajectory</span></span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">(N=</span></span><span class="hljs-number"><span class="hljs-function"><span class="hljs-params"><span class="hljs-number">4</span></span></span></span><span class="hljs-function"><span class="hljs-params">)</span></span></span><span class="hljs-function">:</span></span> sel = FreeCADGui.Selection.getSelection() <span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">def</span></span></span><span class="hljs-function"> </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">prErr</span></span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">()</span></span></span><span class="hljs-function">:</span></span> FreeCAD.Console.PrintError(<span class="hljs-string"><span class="hljs-string">"Error: you should select a traectory and one object\n"</span></span>) <span class="hljs-keyword"><span class="hljs-keyword">if</span></span> (<span class="hljs-keyword"><span class="hljs-keyword">not</span></span> sel): prErr(); <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> <span class="hljs-keyword"><span class="hljs-keyword">None</span></span> L = len(sel) <span class="hljs-keyword"><span class="hljs-keyword">if</span></span>(L != <span class="hljs-number"><span class="hljs-number">2</span></span>): prErr(); <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> <span class="hljs-keyword"><span class="hljs-keyword">None</span></span> <span class="hljs-keyword"><span class="hljs-keyword">if</span></span>(N &lt; <span class="hljs-number"><span class="hljs-number">2</span></span>): FreeCAD.Console.PrintError(<span class="hljs-string"><span class="hljs-string">"Error: N shold be more than 1\n"</span></span>); <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> <span class="hljs-keyword"><span class="hljs-keyword">None</span></span> Traj = sel[<span class="hljs-number"><span class="hljs-number">0</span></span>].Shape <span class="hljs-comment"><span class="hljs-comment">#(a, b) = Traj.ParameterRange Obj = sel[1] TLen = Traj.Length / (N - 1) curPos = 0 doc = FreeCAD.activeDocument() grp = doc.addObject("App::DocumentObjectGroup", "BSplineCopy") try: for i in range(0, N): v = Traj.valueAt(curPos); curPos += TLen newobj = CopyObjAt(Obj, v) grp.addObject(newobj) except: FreeCAD.Console.PrintError("Error: bad selection\n") return None</span></span></code> </pre><br><br><h2>  We draw the bearing </h2><br>  Now, like a ‚Äúwheel‚Äù, we can draw a simple bearing without a separator. <br><br>  To begin with we will draw shells.  Again, ‚Äúon the eye‚Äù we first draw the outlines of broken lines, then draw a circle between them, which we will immediately make inactive.  Next, we will impose restrictions on our figures: the positions of the points, the verticality and horizontality of the sections, the equality of identical lines, the tangential restriction of one point of the furrow in the shells and the surface of the ball, we will introduce some dimensions.  As a result, we get the following sketch: <br><br><img src="http://img4.imageshack.us/img4/8835/b01kk.png"><br><br>  Let's exit the sketch editing mode, select it on the general view and activate the sketch rotation operation.  As a result, we get this nice thing: <br><br><img src="http://img811.imageshack.us/img811/496/b02.png"><br><br>  Now we need to add balls.  To do this, activate the ‚ÄúDraw Sphere‚Äù icon to get the default sphere.  Select it and correct the parameters: make the radius equal to 15 units, and in the position (Placement.Position) make the X coordinate equal to 58 units.  In order to ‚Äúpropagate‚Äù the balls, we still need to calculate the angular diameter of one ball.  The easiest way to do this is to open our sketch again (now it belongs to the ‚ÄúRevolution‚Äù object).  To prevent the shell from interfering, select it and press the spacebar - it will become invisible.  Now draw a segment from the origin to our ball.  Let's make restrictions: we will tie one end of the segment strictly to the origin of coordinates, and the second we will make a tangent to the ball.  Selecting this segment, we activate the angle limit (of course, FreeCAD will swear on an excessive amount of restrictions, but we only need to look).  So, this angle is 14.9882 degrees, roughly speaking - 15 degrees.  Immediately remove this restriction so that FreeCAD does not swear and return to <s>our sheep a</s> general view.  Select the ball and distribute copies of it around the circle every 30 degrees.  By luck, we will need to enter commands similar to the previous item: <br><br><pre> <code class="python hljs"><span class="hljs-keyword"><span class="hljs-keyword">import</span></span> NCopy NCopy.copyCirc(A=App.Vector(<span class="hljs-number"><span class="hljs-number">0</span></span>,<span class="hljs-number"><span class="hljs-number">1</span></span>,<span class="hljs-number"><span class="hljs-number">0</span></span>), N=<span class="hljs-number"><span class="hljs-number">0</span></span>, Ang=<span class="hljs-number"><span class="hljs-number">30</span></span>, moveOriToGrp=<span class="hljs-keyword"><span class="hljs-keyword">True</span></span>)</code> </pre><br><br>  Now let's color our objects a bit.  To make it easier to paint the balls, combine them into one object.  For ‚Äúbeauty‚Äù, change the style of displaying objects from ‚ÄúFlat Lines‚Äù to ‚ÄúShaded‚Äù.  I made the color of the balls ‚Äúgold‚Äù (255, 214, 0), and the color of the shell - ‚Äúsilver‚Äù (192, 192, 192).  You can change the color not through the GUI, but on the command line (only the RGB components must be normalized by one).  If the document is called ‚Äúbearing,‚Äù it will look like this: <br><br><pre> <code class="python hljs">FreeCADGui.getDocument(<span class="hljs-string"><span class="hljs-string">"bearing"</span></span>).getObject(<span class="hljs-string"><span class="hljs-string">"Fusion"</span></span>).ShapeColor = (<span class="hljs-number"><span class="hljs-number">1.00</span></span>,<span class="hljs-number"><span class="hljs-number">0.84</span></span>,<span class="hljs-number"><span class="hljs-number">0.00</span></span>) FreeCADGui.getDocument(<span class="hljs-string"><span class="hljs-string">"bearing"</span></span>).getObject(<span class="hljs-string"><span class="hljs-string">"Revolution"</span></span>).ShapeColor = (<span class="hljs-number"><span class="hljs-number">0.75</span></span>,<span class="hljs-number"><span class="hljs-number">0.75</span></span>,<span class="hljs-number"><span class="hljs-number">0.75</span></span>)</code> </pre><br><br>  Similarly, you can change the type of display: <br><br><pre> <code class="python hljs">FreeCADGui.getDocument(<span class="hljs-string"><span class="hljs-string">"bearing"</span></span>).getObject(<span class="hljs-string"><span class="hljs-string">"Revolution"</span></span>).DisplayMode = <span class="hljs-string"><span class="hljs-string">"Shaded"</span></span> FreeCADGui.getDocument(<span class="hljs-string"><span class="hljs-string">"bearing"</span></span>).getObject(<span class="hljs-string"><span class="hljs-string">"Fusion"</span></span>).DisplayMode = <span class="hljs-string"><span class="hljs-string">"Shaded"</span></span></code> </pre><br><br><img src="http://img542.imageshack.us/img542/8798/b03.png"><br><br>  And you can make a drawing and export it to SVG: <br><br><img src="https://dl.dropbox.com/u/78717568/Const_storage/freecad/bearing.svg"><br><br><h2>  More about script writing </h2><br>  As I have already said, in order to make it possible to launch your commands from the FreeCAD console, you only need to place the files (python modules) with these commands in the ~ / .FreeCAD / Mod / directory or its subdirectories.  However, to make it possible to launch commands from the GUI (‚Äúbuttons‚Äù, ‚Äúmenus‚Äù, etc.), you need to do a little more. <br><br>  First, you need to create an initiation script InitGui.py and place it in a script subdirectory.  This FreeCAD script will launch when viewing the contents of our script directory. <br><br>  The minimum content of this file is: <br><br><pre> <code class="python hljs"><span class="hljs-class"><span class="hljs-keyword"><span class="hljs-class"><span class="hljs-keyword">class</span></span></span><span class="hljs-class"> </span><span class="hljs-title"><span class="hljs-class"><span class="hljs-title">MyWorkbench</span></span></span><span class="hljs-class"> </span><span class="hljs-params"><span class="hljs-class"><span class="hljs-params">( Workbench )</span></span></span><span class="hljs-class">:</span></span> <span class="hljs-keyword"><span class="hljs-keyword">import</span></span>   Icon =     () MenuText = <span class="hljs-string"><span class="hljs-string">" "</span></span> ToolTip = <span class="hljs-string"><span class="hljs-string">"   "</span></span> <span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">def</span></span></span><span class="hljs-function"> </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">Initialize</span></span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">(self)</span></span></span><span class="hljs-function">:</span></span> <span class="hljs-comment"><span class="hljs-comment"># ToolBar list = [     ] self.appendToolbar("  ",list) # Menu list = [     ] self.appendMenu(" ",list) Gui.addWorkbench(MyWorkbench())</span></span></code> </pre><br><br>  "Lists of items" list contain string variables - the names of the classes provided by our toolkit.  Accordingly, for each line of these lists, we must create a corresponding command or class.  When you activate a thumbnail on the taskbar or menu item, the designer of this class will be launched, performing some action.  The minimum content of this class is: <br><br><pre> <code class="python hljs"><span class="hljs-class"><span class="hljs-keyword"><span class="hljs-class"><span class="hljs-keyword">class</span></span></span><span class="hljs-class"> </span><span class="hljs-title"><span class="hljs-class"><span class="hljs-title">OneAction</span></span></span><span class="hljs-class">:</span></span> <span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">def</span></span></span><span class="hljs-function"> </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">Activated</span></span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">(self)</span></span></span><span class="hljs-function">:</span></span> <span class="hljs-comment"><span class="hljs-comment">#Initialize import   ,        def GetResources(self): import   IconPath =     (  ) MenuText = "   " ToolTip = "" return {'Pixmap' : IconPath, 'MenuText': MenuText, 'ToolTip': ToolTip} FreeCADGui.addCommand(' ', OneAction())</span></span></code> </pre><br><br>  The last line tells FreeCAD that our OneAction class will correspond to the line ‚ÄúItem name‚Äù (accordingly, we will put this line in the lists of the initializer class of our toolkit). <br><br>  In order to create new objects, we need to create a separate class for these objects.  The minimum content of this class is: <br><br><pre> <code class="python hljs"><span class="hljs-class"><span class="hljs-keyword"><span class="hljs-class"><span class="hljs-keyword">class</span></span></span><span class="hljs-class"> </span><span class="hljs-title"><span class="hljs-class"><span class="hljs-title">MyObject</span></span></span><span class="hljs-class">:</span></span> <span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">def</span></span></span><span class="hljs-function"> </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">__init__</span></span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">(self, obj, )</span></span></span><span class="hljs-function">:</span></span> <span class="hljs-string"><span class="hljs-string">''' Add new properties to partfeature '''</span></span> obj.addProperty(<span class="hljs-string"><span class="hljs-string">" "</span></span>,<span class="hljs-string"><span class="hljs-string">" "</span></span>,<span class="hljs-string"><span class="hljs-string">""</span></span>,<span class="hljs-string"><span class="hljs-string">""</span></span>).= obj.Proxy = self obj.Shape =    -(obj.ViewObject) <span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">def</span></span></span><span class="hljs-function"> </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">onChanged</span></span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">(self, obj, prop)</span></span></span><span class="hljs-function">:</span></span> ,     prop, obj -   -(obj.ViewObject) <span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">def</span></span></span><span class="hljs-function"> </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">execute</span></span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">(self, obj)</span></span></span><span class="hljs-function">:</span></span> ,   <span class="hljs-string"><span class="hljs-string">""</span></span>  -(obj.ViewObject)</code> </pre><br><br>  The provider class provides the GUI with resources (icons, etc.). <br><br>  Examples of scripts can be viewed in the FreeCAD resource directories and in the official documentation. <br><br>  Finally, I will give examples.  The first example is drawn without using the command console: <br><br><img src="http://img803.imageshack.us/img803/8384/46297705.jpg"><br><br>  The second example is with simple scripts that allow you to draw lenses.  That's where, as they say, "it is better to lose a day, but then in an hour to fly."  Here is the code: <br><br><pre> <code class="python hljs"><span class="hljs-keyword"><span class="hljs-keyword">import</span></span> Lens a=[[<span class="hljs-number"><span class="hljs-number">8</span></span>,<span class="hljs-number"><span class="hljs-number">6</span></span>,<span class="hljs-number"><span class="hljs-number">1</span></span>,<span class="hljs-number"><span class="hljs-number">6</span></span>,<span class="hljs-number"><span class="hljs-number">3</span></span>], [<span class="hljs-number"><span class="hljs-number">10</span></span>,<span class="hljs-number"><span class="hljs-number">-15</span></span>,<span class="hljs-number"><span class="hljs-number">2.5</span></span>,<span class="hljs-number"><span class="hljs-number">8</span></span>,<span class="hljs-number"><span class="hljs-number">5</span></span>], [<span class="hljs-number"><span class="hljs-number">-16</span></span>,<span class="hljs-number"><span class="hljs-number">10</span></span>,<span class="hljs-number"><span class="hljs-number">0.5</span></span>,<span class="hljs-number"><span class="hljs-number">6</span></span>,<span class="hljs-number"><span class="hljs-number">7</span></span>], [<span class="hljs-number"><span class="hljs-number">-8</span></span>,<span class="hljs-number"><span class="hljs-number">-6</span></span>,<span class="hljs-number"><span class="hljs-number">0.5</span></span>,<span class="hljs-number"><span class="hljs-number">4</span></span>,<span class="hljs-number"><span class="hljs-number">3</span></span>], [<span class="hljs-number"><span class="hljs-number">3</span></span>,<span class="hljs-number"><span class="hljs-number">3</span></span>,<span class="hljs-number"><span class="hljs-number">0.2</span></span>,<span class="hljs-number"><span class="hljs-number">2</span></span>,<span class="hljs-number"><span class="hljs-number">1</span></span>], [<span class="hljs-number"><span class="hljs-number">0</span></span>,<span class="hljs-number"><span class="hljs-number">0</span></span>,<span class="hljs-number"><span class="hljs-number">0.1</span></span>,<span class="hljs-number"><span class="hljs-number">1</span></span>,<span class="hljs-number"><span class="hljs-number">0.1</span></span>], [<span class="hljs-number"><span class="hljs-number">0</span></span>,<span class="hljs-number"><span class="hljs-number">3</span></span>,<span class="hljs-number"><span class="hljs-number">.3</span></span>,<span class="hljs-number"><span class="hljs-number">1</span></span>]] Lens.makeLensBench(a) b=[[<span class="hljs-number"><span class="hljs-number">-10</span></span>,<span class="hljs-number"><span class="hljs-number">8</span></span>,<span class="hljs-number"><span class="hljs-number">0.1</span></span>,<span class="hljs-number"><span class="hljs-number">6</span></span>], [<span class="hljs-number"><span class="hljs-number">8</span></span>,<span class="hljs-number"><span class="hljs-number">16</span></span>,<span class="hljs-number"><span class="hljs-number">0.5</span></span>,<span class="hljs-number"><span class="hljs-number">6</span></span>], [<span class="hljs-number"><span class="hljs-number">16</span></span>,<span class="hljs-number"><span class="hljs-number">-9</span></span>,<span class="hljs-number"><span class="hljs-number">1</span></span>,<span class="hljs-number"><span class="hljs-number">6</span></span>]] Lens.makeLensBench(b,App.Vector(<span class="hljs-number"><span class="hljs-number">0</span></span>,<span class="hljs-number"><span class="hljs-number">10</span></span>,<span class="hljs-number"><span class="hljs-number">0</span></span>))</code> </pre><br><br>  allows you to get this: <br><br><img src="http://img14.imageshack.us/img14/5307/lensqg.png"><br><br>  In the <a href="">video</a> you can see how this model looks. <br><br>  Interested advise to go <a href="http://freecad-tutorial.blogspot.com/">here</a> and see more many different examples. <br><br>  UPD: <a href="">here is an example of</a> real work performed in a fricade (cryostat). </div><p>Source: <a href="https://habr.com/ru/post/145985/">https://habr.com/ru/post/145985/</a></p>
<section class="more-articles-navigation-panel js-more-articles-navigation-panel">
<h4>More articles:</h4>
<nav class="list-of-articles-container js-list-of-articles-container"><ul class="list-of-pages js-list-of-pages">
<li><a href="../145980/index.html">Setting up a correct shutdown of guest Windows 2003 in qemu-kvm Linux</a></li>
<li><a href="../145981/index.html">Does your VDS / VPS / Dedicated hoster alert you about reboots and shutdowns?</a></li>
<li><a href="../145982/index.html">Trigger Timer for Nikon</a></li>
<li><a href="../145983/index.html">In Scotland, plan to create an underwater power plant</a></li>
<li><a href="../145984/index.html">Wind noise can also be "copyright material"</a></li>
<li><a href="../145986/index.html">Configuring OS Inferno</a></li>
<li><a href="../145987/index.html">VTech has released tablets for kids</a></li>
<li><a href="../145988/index.html">OAuth in practice. Authentication and authorization of site users through popular social networks</a></li>
<li><a href="../145991/index.html">Do-it-yourself PID controller</a></li>
<li><a href="../145993/index.html">Catalog of articles on OS Inferno</a></li>
</ul></nav>
</section><br />
<a href="../../allArticles.html"><strong>All Articles</strong></a>
<script src="../../js/main.js"></script>

<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
  (function (d, w, c) {
      (w[c] = w[c] || []).push(function() {
          try {
              w.yaCounter52496797 = new Ya.Metrika({
                  id:52496797,
                  clickmap:true,
                  trackLinks:true,
                  accurateTrackBounce:true,
                  webvisor:true
              });
          } catch(e) { }
      });

      var n = d.getElementsByTagName("script")[0],
          s = d.createElement("script"),
          f = function () { n.parentNode.insertBefore(s, n); };
      s.type = "text/javascript";
      s.async = true;
      s.src = "https://mc.yandex.ru/metrika/watch.js";

      if (w.opera == "[object Opera]") {
          d.addEventListener("DOMContentLoaded", f, false);
      } else { f(); }
  })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/52496797" style="position:absolute; left:-9999px;" alt="" /></div></noscript>

<!-- Google Analytics -->
  <script>
    window.ga = function () { ga.q.push(arguments) }; ga.q = []; ga.l = +new Date;
    ga('create', 'UA-134931760-1', 'auto'); ga('send', 'pageview')
  </script>
  <script src="https://www.google-analytics.com/analytics.js" async defer></script>

</section>

  <footer class="page-footer">
    <div class="page-footer-legal-info-container page-footer-element">
      <p>
        Weekly-Geekly | <span class="page-footer-legal-info-year js-page-footer-legal-info-year">2019</span>
      </p>
    </div>
    <div class="page-footer-counters-container page-footer-element">
      <a class="page-footer-counter-clustrmap" href='#'  title='Visit tracker'><img src='https://clustrmaps.com/map_v2.png?cl=698e5a&w=271&t=t&d=6iCFw7uJz0zcOaoxz5k5PcLCJUzv2WG8G5V8M3U6Rc4&co=3a3a3a&ct=ffffff'/></a>
    </div>
  </footer>
</body>

</html>