<!doctype html>
<html class="no-js" lang="en">

<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-134931760-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-134931760-1');
  </script>

  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>AutoCAD: Communication with external data</title>
  <link rel="icon" type="image/x-icon" href="/favicon.ico" />
  <meta name="description" content="Often, users want to associate drawing objects with external data ‚Äî an Excel spreadsheet, a database, or simply a text or xml file. Of course, in Auto...">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="../../css/main.css">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="../../js/vendors/jquery-3.3.1.min.js"><\/script>')</script>

  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <script>
       (adsbygoogle = window.adsbygoogle || []).push({
            google_ad_client: "ca-pub-6974184241884155",
            enable_page_level_ads: true
       });
  </script>
</head>

<body>
  <!--[if lte IE 9]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
  <![endif]-->
  <header class="page-header js-page-header">
    <a class="page-header-logo-container" href="https://weekly-geekly.github.io/index.html"></a>
    <div class="page-header-text">Geekly Articles each Day</div>
  </header>
  <nav class="page-headings-container js-page-headings-container"></nav>
  <div class="tools-bar js-tools-bar">
    <!-- <a href="../../search.html" title="Search">üîé</a> -->
    <a class="js-list-of-headings-button" data-state="closed" href="#" title="Headings">üìú</a>
    <a class="js-go-to-top-button" href="#" title="Go to Top">‚¨ÜÔ∏è</a>
    <a class="js-go-to-bottom-button" href="#" title="Go to Bottom">‚¨áÔ∏è</a>
  </div>
  <a href="http://bit.ly/donateToWeeklyGeekly" class="donate-btn">DONATE</a>
  <section class="page js-page"><h1>AutoCAD: Communication with external data</h1><div class="post__text post__text-html js-mediator-article">  Often, users want to associate drawing objects with external data ‚Äî an Excel spreadsheet, a database, or simply a text or xml file.  Of course, in AutoCAD, there are many ways to interact with external data: _DataLink, dbConnect, attin, _script.  But all these tools require ‚Äúmany clicks‚Äù and do not provide the necessary interaction.  The user wants the drawing objects to be automatically aligned with the external data, with minimal participation.  An exemplary example of such interaction is FDO in AutoCAD Map 3D - when, after connecting to the source, we immediately receive its content as graphics (and, if desired, even with signatures) and to synchronize with the source, it is enough to update the layer (one command).  But this is a special (and therefore limited) GIS tool that is not suitable for everyone.  And then it remains only to apply programming, the benefit there is a huge number of ways to do it - Lisp, C ++, .Net, Delphi, Python, etc. <br><a name="habracut"></a><br>  One way to establish such a link to a data source is to create a class that will be responsible for linking to data or simply aggregate this data for import / export.  In this article I will show an example of this class, which: <br><br><ol><li>  Draws itself (but not Custom object *) </li><li>  Has its own data and monitors their relevance. </li><li>  Can import / export itself to XML </li></ol><br>  * Custom object is a ObjectARX functional that allows you to create your own graphic primitives, but they are implemented as separate libraries, and if they are not present, the Custom object turns into a proxy object <s>pumpkin</s> .  Objects of vertical solutions AutoDESK is a Custom object and, in order to see them in the ‚Äúbare‚Äù AutoCAD, you need to set the corresponding Object Enabler. <br><br>  In AutoCAD, a programmer has several tools for storing his own data in a drawing, these are XData and XRecord.  But these are very limited tools and access to this data is only available from AutoCAD.  Therefore, we will use an external data source, and connect them with primitives in the drawing, via Handle. 
      <br>
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <ins class="adsbygoogle"
          style="display:block; text-align:center;"
          data-ad-layout="in-article"
          data-ad-format="fluid"
          data-ad-client="ca-pub-6974184241884155"
          data-ad-slot="8945601208"></ins>
        <script>
          (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
      <br>
      Our object will draw a circle, as well as a text label containing the radius of this circle, but this method allows you to create any primitives (for example, Solid3d or NurbSurface) - if only they had a Handle.  We will need methods to draw the Object and Tags.  But most importantly, we need a method to track the change of the object, an event handler that we hang on the Modified event.  We also need methods for updating primitives and exporting to XML.  Well, enough, fewer words - more code. <br><br><div class="spoiler">  <b class="spoiler_title">Class mycircle</b> <div class="spoiler_text"><pre><code class="hljs pgsql">Imports <span class="hljs-keyword"><span class="hljs-keyword">System</span></span>.Xml Imports Autodesk.AutoCAD.DatabaseServices Imports Autodesk.AutoCAD.EditorInput Imports Autodesk.AutoCAD.Geometry <span class="hljs-built_in"><span class="hljs-built_in">Public</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Class</span></span> MyCircle Private fCenter <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> Point3d Private fRadius <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> <span class="hljs-type"><span class="hljs-type">Double</span></span> Private <span class="hljs-type"><span class="hljs-type">OID</span></span> <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> ObjectId Private textID <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> ObjectId <span class="hljs-built_in"><span class="hljs-built_in">Public</span></span> Sub <span class="hljs-built_in"><span class="hljs-built_in">New</span></span>(cp <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> Point3d, r <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> <span class="hljs-type"><span class="hljs-type">Double</span></span>, db <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Database</span></span>) Me.fCenter = cp Me.fRadius = R <span class="hljs-string"><span class="hljs-string">' Me.DrawMe(db) Me.DrawLebel() End Sub Public Sub New(MyCircleData As XmlElement, db As Database) Dim wHandle As New Handle(Long.Parse(MyCircleData.GetAttribute("Handle"), Globalization.NumberStyles.HexNumber)) OID = New ObjectId Me.fCenter = Me.ParsePoint(MyCircleData.GetAttribute("Center")) Me.fRadius = MyCircleData.GetAttribute("Radius") If db.TryGetObjectId(wHandle, OID) Then Me.UpgradeMe() Else Me.DrawMe(db) End If Me.DrawLebel() End Sub Public Sub UpgradeMe() Using acTrans As Transaction = OID.Database.TransactionManager.StartTransaction() Dim wDBObj As Circle = OID.GetObject(OpenMode.ForWrite) RemoveHandler wDBObj.Modified, AddressOf CirMod wDBObj.Radius = Me.fRadius wDBObj.Center = Me.fCenter wDBObj.UpgradeOpen() AddHandler wDBObj.Modified, AddressOf CirMod acTrans.Commit() End Using End Sub Public Sub UpgradeLabel() Using acTrans As Transaction = OID.Database.TransactionManager.StartTransaction() Dim acText As DBText = textID.GetObject(OpenMode.ForWrite) acText.Position = Me.fCenter acText.TextString = Me.fRadius acText.UpgradeOpen() acTrans.Commit() End Using End Sub Public Sub DrawMe(db As Database) Using acTrans As Transaction = db.TransactionManager.StartTransaction() Dim cNewCircle As New Circle(Me.fCenter, New Vector3d(0, 0, 1), Me.fRadius) '</span></span>    (    ) Dim btrCurrSpace <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> BlockTableRecord = acTrans.GetObject(db.CurrentSpaceId, OpenMode.ForWrite) <span class="hljs-string"><span class="hljs-string">'       OID = btrCurrSpace.AppendEntity(cNewCircle) acTrans.AddNewlyCreatedDBObject(cNewCircle, True) AddHandler cNewCircle.Modified, AddressOf CirMod '</span></span>  acTrans.<span class="hljs-keyword"><span class="hljs-keyword">Commit</span></span>() <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Using</span></span> <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> Sub <span class="hljs-built_in"><span class="hljs-built_in">Public</span></span> Sub DrawLebel() <span class="hljs-keyword"><span class="hljs-keyword">If</span></span> textID.<span class="hljs-keyword"><span class="hljs-keyword">IsNull</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Then</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Using</span></span> acTrans <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Transaction</span></span> = <span class="hljs-type"><span class="hljs-type">OID</span></span>.<span class="hljs-keyword"><span class="hljs-keyword">Database</span></span>.TransactionManager.StartTransaction() Dim acBlkTbl <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> BlockTable acBlkTbl = acTrans.GetObject(<span class="hljs-type"><span class="hljs-type">OID</span></span>.<span class="hljs-keyword"><span class="hljs-keyword">Database</span></span>.BlockTableId, OpenMode.ForRead) Dim acBlkTblRec <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> BlockTableRecord acBlkTblRec = acTrans.GetObject(acBlkTbl(BlockTableRecord.ModelSpace), OpenMode.ForWrite) Dim acText <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> <span class="hljs-built_in"><span class="hljs-built_in">New</span></span> DBText() acText.SetDatabaseDefaults() acText.Position = Me.fCenter acText.Height = <span class="hljs-number"><span class="hljs-number">2</span></span> acText.TextString = Me.fRadius textID = acBlkTblRec.AppendEntity(acText) acTrans.AddNewlyCreatedDBObject(acText, <span class="hljs-keyword"><span class="hljs-keyword">True</span></span>) acTrans.<span class="hljs-keyword"><span class="hljs-keyword">Commit</span></span>() <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Using</span></span> <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> <span class="hljs-keyword"><span class="hljs-keyword">If</span></span> <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> Sub <span class="hljs-built_in"><span class="hljs-built_in">Public</span></span> Sub EraseLebel() <span class="hljs-keyword"><span class="hljs-keyword">If</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Not</span></span> textID.<span class="hljs-keyword"><span class="hljs-keyword">IsNull</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Then</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Using</span></span> acTrans <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Transaction</span></span> = <span class="hljs-type"><span class="hljs-type">OID</span></span>.<span class="hljs-keyword"><span class="hljs-keyword">Database</span></span>.TransactionManager.StartTransaction() Dim wDBObj <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> DBText = textID.GetObject(OpenMode.ForWrite) wDBObj.Erase() wDBObj.UpgradeOpen() acTrans.<span class="hljs-keyword"><span class="hljs-keyword">Commit</span></span>() <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Using</span></span> <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> <span class="hljs-keyword"><span class="hljs-keyword">If</span></span> <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> Sub <span class="hljs-built_in"><span class="hljs-built_in">Public</span></span> Sub CirMod(ByVal senderObj <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Object</span></span>, ByVal evtArgs <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> EventArgs) <span class="hljs-keyword"><span class="hljs-keyword">Using</span></span> acTrans <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Transaction</span></span> = <span class="hljs-type"><span class="hljs-type">OID</span></span>.<span class="hljs-keyword"><span class="hljs-keyword">Database</span></span>.TransactionManager.StartTransaction() Dim wDBObj <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> <span class="hljs-type"><span class="hljs-type">Circle</span></span> = <span class="hljs-type"><span class="hljs-type">OID</span></span>.GetObject(OpenMode.ForRead) Me.fCenter = wDBObj.Center Me.fRadius = wDBObj.Radius UpgradeLabel() acTrans.<span class="hljs-keyword"><span class="hljs-keyword">Commit</span></span>() <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Using</span></span> <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> Sub Private <span class="hljs-keyword"><span class="hljs-keyword">Function</span></span> ParsePoint(wStr <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> String) <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> Point3d wStr = wStr.Replace("(", "") wStr = wStr.Replace(")", "") Dim Arr() <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> String = wStr.Split(",") <span class="hljs-keyword"><span class="hljs-keyword">Return</span></span> <span class="hljs-built_in"><span class="hljs-built_in">New</span></span> Point3d(<span class="hljs-type"><span class="hljs-type">Double</span></span>.Parse(Arr(<span class="hljs-number"><span class="hljs-number">0</span></span>)), <span class="hljs-type"><span class="hljs-type">Double</span></span>.Parse(Arr(<span class="hljs-number"><span class="hljs-number">1</span></span>)), <span class="hljs-type"><span class="hljs-type">Double</span></span>.Parse(Arr(<span class="hljs-number"><span class="hljs-number">2</span></span>))) <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Function</span></span> <span class="hljs-built_in"><span class="hljs-built_in">Public</span></span> Property Center <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> Point3d <span class="hljs-keyword"><span class="hljs-keyword">Get</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Return</span></span> Me.fCenter <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Get</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Set</span></span>(<span class="hljs-keyword"><span class="hljs-keyword">value</span></span> <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> Point3d) Me.fCenter = <span class="hljs-keyword"><span class="hljs-keyword">value</span></span> Me.UpgradeMe() <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Set</span></span> <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> Property <span class="hljs-built_in"><span class="hljs-built_in">Public</span></span> Sub Print(wEditor <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> Editor) <span class="hljs-keyword"><span class="hljs-keyword">Using</span></span> acTrans <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Transaction</span></span> = <span class="hljs-type"><span class="hljs-type">OID</span></span>.<span class="hljs-keyword"><span class="hljs-keyword">Database</span></span>.TransactionManager.StartTransaction() wEditor.WriteMessage("Handle: " &amp; <span class="hljs-type"><span class="hljs-type">OID</span></span>.Handle.ToString &amp; Environment.NewLine) Dim wDBObj <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> <span class="hljs-type"><span class="hljs-type">Circle</span></span> = <span class="hljs-type"><span class="hljs-type">OID</span></span>.GetObject(OpenMode.ForRead) wEditor.WriteMessage("Radius: " &amp; wDBObj.Radius &amp; Environment.NewLine) wEditor.WriteMessage("Center: " &amp; wDBObj.Center.ToString &amp; Environment.NewLine) <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Using</span></span> <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> Sub <span class="hljs-built_in"><span class="hljs-built_in">Public</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Function</span></span> ToXML(wDoc <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> XmlDocument) <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> XmlElement Dim res <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> XmlElement = wDoc.CreateElement("MyCircle") <span class="hljs-keyword"><span class="hljs-keyword">Using</span></span> acTrans <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Transaction</span></span> = <span class="hljs-type"><span class="hljs-type">OID</span></span>.<span class="hljs-keyword"><span class="hljs-keyword">Database</span></span>.TransactionManager.StartTransaction() res.SetAttribute("Handle", Me.OID.Handle.ToString) Dim wDBObj <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> <span class="hljs-type"><span class="hljs-type">Circle</span></span> = <span class="hljs-type"><span class="hljs-type">OID</span></span>.GetObject(OpenMode.ForRead) res.SetAttribute("Radius", wDBObj.Radius) res.SetAttribute("Center", wDBObj.Center.ToString) <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Using</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Return</span></span> res <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Function</span></span> <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Class</span></span></code> </pre> <br></div></div><br>  A few explanations: <br><br><pre> <code class="hljs css"><span class="hljs-selector-tag"><span class="hljs-selector-tag">Imports</span></span> <span class="hljs-selector-tag"><span class="hljs-selector-tag">Autodesk</span></span><span class="hljs-selector-class"><span class="hljs-selector-class">.AutoCAD</span></span><span class="hljs-selector-class"><span class="hljs-selector-class">.DatabaseServices</span></span> <span class="hljs-selector-tag"><span class="hljs-selector-tag">Imports</span></span> <span class="hljs-selector-tag"><span class="hljs-selector-tag">Autodesk</span></span><span class="hljs-selector-class"><span class="hljs-selector-class">.AutoCAD</span></span><span class="hljs-selector-class"><span class="hljs-selector-class">.EditorInput</span></span> <span class="hljs-selector-tag"><span class="hljs-selector-tag">Imports</span></span> <span class="hljs-selector-tag"><span class="hljs-selector-tag">Autodesk</span></span><span class="hljs-selector-class"><span class="hljs-selector-class">.AutoCAD</span></span><span class="hljs-selector-class"><span class="hljs-selector-class">.Geometry</span></span></code> </pre><br>  Did you remember to connect cmgd.dll, acdbmgd.dll, accoremgd.dll (AcAd&gt; = 2013)? <br><br><pre> <code class="vbscript hljs"> <span class="hljs-keyword"><span class="hljs-keyword">Private</span></span> fCenter As Point3d <span class="hljs-keyword"><span class="hljs-keyword">Private</span></span> fRadius As Double</code> </pre><br>  The object's own data, yes, these are properties of a primitive, but this is an example. <br><br><pre> <code class="vbscript hljs"> <span class="hljs-keyword"><span class="hljs-keyword">Private</span></span> OID As ObjectId <span class="hljs-comment"><span class="hljs-comment">' Private textID As ObjectId '</span></span></code> </pre><br>  References to drawing primitives. <br><br><pre> <code class="hljs pgsql"> <span class="hljs-built_in"><span class="hljs-built_in">Public</span></span> Sub DrawMe(db <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Database</span></span>) <span class="hljs-keyword"><span class="hljs-keyword">Using</span></span> acTrans <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Transaction</span></span> = db.TransactionManager.StartTransaction() Dim cNewCircle <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> <span class="hljs-built_in"><span class="hljs-built_in">New</span></span> Circle(Me.fCenter, <span class="hljs-built_in"><span class="hljs-built_in">New</span></span> Vector3d(<span class="hljs-number"><span class="hljs-number">0</span></span>, <span class="hljs-number"><span class="hljs-number">0</span></span>, <span class="hljs-number"><span class="hljs-number">1</span></span>), Me.fRadius) <span class="hljs-string"><span class="hljs-string">'    (    ) Dim btrCurrSpace As BlockTableRecord = acTrans.GetObject(db.CurrentSpaceId, OpenMode.ForWrite) '</span></span>       <span class="hljs-type"><span class="hljs-type">OID</span></span> = btrCurrSpace.AppendEntity(cNewCircle) acTrans.AddNewlyCreatedDBObject(cNewCircle, <span class="hljs-keyword"><span class="hljs-keyword">True</span></span>) AddHandler cNewCircle.Modified, AddressOf CirMod <span class="hljs-string"><span class="hljs-string">'  acTrans.Commit() End Using End Sub</span></span></code> </pre><br>  We draw the object itself, and at the same time we remember the reference to the primitive and, most importantly, we hang the handler to change the object. <br><br><pre> <code class="hljs pgsql"> <span class="hljs-built_in"><span class="hljs-built_in">Public</span></span> Sub CirMod(ByVal senderObj <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Object</span></span>, ByVal evtArgs <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> EventArgs) <span class="hljs-keyword"><span class="hljs-keyword">Using</span></span> acTrans <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Transaction</span></span> = <span class="hljs-type"><span class="hljs-type">OID</span></span>.<span class="hljs-keyword"><span class="hljs-keyword">Database</span></span>.TransactionManager.StartTransaction() <span class="hljs-string"><span class="hljs-string">'Dim acText As DBText = textID.GetObject(OpenMode.ForWrite) Dim wDBObj As Circle = OID.GetObject(OpenMode.ForRead) Me.fCenter = wDBObj.Center Me.fRadius = wDBObj.Radius UpgradeLabel() acTrans.Commit() End Using End Sub</span></span></code> </pre><br>  We process the change of the object - we obtain new values ‚Äã‚Äãof the properties of the object, we update the Label. <br><br><pre> <code class="hljs pgsql"> <span class="hljs-built_in"><span class="hljs-built_in">Public</span></span> Sub DrawLebel() <span class="hljs-keyword"><span class="hljs-keyword">If</span></span> textID.<span class="hljs-keyword"><span class="hljs-keyword">IsNull</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Then</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Using</span></span> acTrans <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Transaction</span></span> = <span class="hljs-type"><span class="hljs-type">OID</span></span>.<span class="hljs-keyword"><span class="hljs-keyword">Database</span></span>.TransactionManager.StartTransaction() Dim acBlkTbl <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> BlockTable acBlkTbl = acTrans.GetObject(<span class="hljs-type"><span class="hljs-type">OID</span></span>.<span class="hljs-keyword"><span class="hljs-keyword">Database</span></span>.BlockTableId, OpenMode.ForRead) Dim acBlkTblRec <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> BlockTableRecord acBlkTblRec = acTrans.GetObject(acBlkTbl(BlockTableRecord.ModelSpace), OpenMode.ForWrite) Dim acText <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> <span class="hljs-built_in"><span class="hljs-built_in">New</span></span> DBText() acText.SetDatabaseDefaults() acText.Position = Me.fCenter acText.Height = <span class="hljs-number"><span class="hljs-number">2</span></span> acText.TextString = Me.fRadius textID = acBlkTblRec.AppendEntity(acText) acTrans.AddNewlyCreatedDBObject(acText, <span class="hljs-keyword"><span class="hljs-keyword">True</span></span>) acTrans.<span class="hljs-keyword"><span class="hljs-keyword">Commit</span></span>() <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Using</span></span> <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> <span class="hljs-keyword"><span class="hljs-keyword">If</span></span> <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> Sub</code> </pre><br>  Draw object label. <br><br><pre> <code class="hljs pgsql"> <span class="hljs-built_in"><span class="hljs-built_in">Public</span></span> Sub <span class="hljs-built_in"><span class="hljs-built_in">New</span></span>(MyCircleData <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> XmlElement, db <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Database</span></span>) Dim wHandle <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> <span class="hljs-built_in"><span class="hljs-built_in">New</span></span> Handle(Long.Parse(MyCircleData.GetAttribute("Handle"), Globalization.NumberStyles.HexNumber)) <span class="hljs-type"><span class="hljs-type">OID</span></span> = <span class="hljs-built_in"><span class="hljs-built_in">New</span></span> ObjectId Me.fCenter = Me.ParsePoint(MyCircleData.GetAttribute("Center")) Me.fRadius = MyCircleData.GetAttribute("Radius") <span class="hljs-keyword"><span class="hljs-keyword">If</span></span> db.TryGetObjectId(wHandle, <span class="hljs-type"><span class="hljs-type">OID</span></span>) <span class="hljs-keyword"><span class="hljs-keyword">Then</span></span> Me.UpgradeMe() <span class="hljs-keyword"><span class="hljs-keyword">Else</span></span> Me.DrawMe(db) <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> <span class="hljs-keyword"><span class="hljs-keyword">If</span></span> Me.DrawLebel() <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> Sub <span class="hljs-built_in"><span class="hljs-built_in">Public</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Function</span></span> ToXML(wDoc <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> XmlDocument) <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> XmlElement Dim res <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> XmlElement = wDoc.CreateElement("MyCircle") <span class="hljs-keyword"><span class="hljs-keyword">Using</span></span> acTrans <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Transaction</span></span> = <span class="hljs-type"><span class="hljs-type">OID</span></span>.<span class="hljs-keyword"><span class="hljs-keyword">Database</span></span>.TransactionManager.StartTransaction() res.SetAttribute("Handle", Me.OID.Handle.ToString) Dim wDBObj <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> <span class="hljs-type"><span class="hljs-type">Circle</span></span> = <span class="hljs-type"><span class="hljs-type">OID</span></span>.GetObject(OpenMode.ForRead) res.SetAttribute("Radius", wDBObj.Radius) res.SetAttribute("Center", wDBObj.Center.ToString) <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Using</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Return</span></span> res <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Function</span></span></code> </pre><br>  Import / export to XML. <br><br>  Well, of course, we need teams in AutoCAD to work with our class. <br><br><div class="spoiler">  <b class="spoiler_title">Command class</b> <div class="spoiler_text"><pre> <code class="hljs pgsql">Imports Autodesk.AutoCAD.Runtime Imports AppServ = Autodesk.AutoCAD.ApplicationServices Imports Autodesk.AutoCAD.DatabaseServices Imports Autodesk.AutoCAD.EditorInput Imports Autodesk.AutoCAD.Geometry Imports <span class="hljs-keyword"><span class="hljs-keyword">System</span></span>.Windows.Forms Imports <span class="hljs-keyword"><span class="hljs-keyword">System</span></span>.Xml <span class="hljs-built_in"><span class="hljs-built_in">Public</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Class</span></span> CommandClass Dim wList <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> List(<span class="hljs-keyword"><span class="hljs-keyword">Of</span></span> MyCircle) = <span class="hljs-keyword"><span class="hljs-keyword">Nothing</span></span> &lt;CommandMethod("CrMyCircle")&gt; _ <span class="hljs-built_in"><span class="hljs-built_in">Public</span></span> Sub CrMyCircle() <span class="hljs-keyword"><span class="hljs-keyword">If</span></span> wList <span class="hljs-keyword"><span class="hljs-keyword">Is</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Nothing</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Then</span></span> wList = <span class="hljs-built_in"><span class="hljs-built_in">New</span></span> List(<span class="hljs-keyword"><span class="hljs-keyword">Of</span></span> MyCircle) Dim acDoc <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> AppServ.Document = AppServ.Application.DocumentManager.MdiActiveDocument Dim acCurDb <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Database</span></span> = acDoc.<span class="hljs-keyword"><span class="hljs-keyword">Database</span></span> Dim pPtRes <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> PromptPointResult = acDoc.Editor.GetPoint(" : ") <span class="hljs-keyword"><span class="hljs-keyword">If</span></span> (pPtRes.Status = PromptStatus.OK) <span class="hljs-keyword"><span class="hljs-keyword">Then</span></span> Dim wPrmtDistOpt <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> <span class="hljs-built_in"><span class="hljs-built_in">New</span></span> PromptDistanceOptions(" : ") wPrmtDistOpt.BasePoint = pPtRes.<span class="hljs-keyword"><span class="hljs-keyword">Value</span></span> wPrmtDistOpt.UseBasePoint = <span class="hljs-keyword"><span class="hljs-keyword">True</span></span> Dim pDistRes <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> PromptDoubleResult = acDoc.Editor.GetDistance(wPrmtDistOpt) <span class="hljs-keyword"><span class="hljs-keyword">If</span></span> (pDistRes.Status = PromptStatus.OK) <span class="hljs-keyword"><span class="hljs-keyword">Then</span></span> wList.<span class="hljs-keyword"><span class="hljs-keyword">Add</span></span>(<span class="hljs-built_in"><span class="hljs-built_in">New</span></span> MyCircle(pPtRes.<span class="hljs-keyword"><span class="hljs-keyword">Value</span></span>, pDistRes.<span class="hljs-keyword"><span class="hljs-keyword">Value</span></span>, acCurDb)) <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> <span class="hljs-keyword"><span class="hljs-keyword">If</span></span> <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> <span class="hljs-keyword"><span class="hljs-keyword">If</span></span> <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> Sub &lt;CommandMethod("SaveToXML")&gt; _ <span class="hljs-built_in"><span class="hljs-built_in">Public</span></span> Sub SaveToXML() Dim nDialog <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> <span class="hljs-built_in"><span class="hljs-built_in">New</span></span> SaveFileDialog nDialog.<span class="hljs-keyword"><span class="hljs-keyword">Filter</span></span> = "XML|*.xml" Dim wDoc <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> <span class="hljs-built_in"><span class="hljs-built_in">New</span></span> XmlDocument wDoc.LoadXml("&lt;?xml version=""1.0"" encoding=""utf-8""?&gt;&lt;MyCircleList/&gt;") <span class="hljs-keyword"><span class="hljs-keyword">If</span></span> wList IsNot <span class="hljs-keyword"><span class="hljs-keyword">Nothing</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Then</span></span> wList.<span class="hljs-keyword"><span class="hljs-keyword">ForEach</span></span>(Sub(obj) wDoc.DocumentElement.AppendChild(obj.ToXML(wDoc))) <span class="hljs-keyword"><span class="hljs-keyword">If</span></span> nDialog.ShowDialog = DialogResult.OK <span class="hljs-keyword"><span class="hljs-keyword">Then</span></span> wDoc.Save(nDialog.FileName) <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> <span class="hljs-keyword"><span class="hljs-keyword">If</span></span> <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> Sub &lt;CommandMethod("LoadFromXML")&gt; _ <span class="hljs-built_in"><span class="hljs-built_in">Public</span></span> Sub LoadFromXML() Dim nDialog <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> <span class="hljs-built_in"><span class="hljs-built_in">New</span></span> OpenFileDialog nDialog.<span class="hljs-keyword"><span class="hljs-keyword">Filter</span></span> = "XML|*.xml" Dim wDoc <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> <span class="hljs-built_in"><span class="hljs-built_in">New</span></span> XmlDocument Dim done <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> <span class="hljs-type"><span class="hljs-type">Boolean</span></span> = <span class="hljs-keyword"><span class="hljs-keyword">False</span></span> <span class="hljs-keyword"><span class="hljs-keyword">If</span></span> nDialog.ShowDialog = DialogResult.OK <span class="hljs-keyword"><span class="hljs-keyword">Then</span></span> wDoc.<span class="hljs-keyword"><span class="hljs-keyword">Load</span></span>(nDialog.FileName) done = <span class="hljs-keyword"><span class="hljs-keyword">True</span></span> <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> <span class="hljs-keyword"><span class="hljs-keyword">If</span></span> <span class="hljs-keyword"><span class="hljs-keyword">If</span></span> done <span class="hljs-keyword"><span class="hljs-keyword">Then</span></span> <span class="hljs-keyword"><span class="hljs-keyword">If</span></span> wList <span class="hljs-keyword"><span class="hljs-keyword">Is</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Nothing</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Then</span></span> wList = <span class="hljs-built_in"><span class="hljs-built_in">New</span></span> List(<span class="hljs-keyword"><span class="hljs-keyword">Of</span></span> MyCircle) Dim acDoc <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> AppServ.Document = AppServ.Application.DocumentManager.MdiActiveDocument Dim acCurDb <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Database</span></span> = acDoc.<span class="hljs-keyword"><span class="hljs-keyword">Database</span></span> <span class="hljs-keyword"><span class="hljs-keyword">For</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Each</span></span> ch <span class="hljs-keyword"><span class="hljs-keyword">In</span></span> wDoc.DocumentElement.ChildNodes wList.<span class="hljs-keyword"><span class="hljs-keyword">Add</span></span>(<span class="hljs-built_in"><span class="hljs-built_in">New</span></span> MyCircle(ch, acCurDb)) Next <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> <span class="hljs-keyword"><span class="hljs-keyword">If</span></span> <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> Sub &lt;CommandMethod("DrawLabel")&gt; _ <span class="hljs-built_in"><span class="hljs-built_in">Public</span></span> Sub DrawLabel() <span class="hljs-keyword"><span class="hljs-keyword">If</span></span> wList IsNot <span class="hljs-keyword"><span class="hljs-keyword">Nothing</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Then</span></span> wList.<span class="hljs-keyword"><span class="hljs-keyword">ForEach</span></span>(Sub(obj) obj.DrawLebel()) <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> Sub &lt;CommandMethod("EraseLabel")&gt; _ <span class="hljs-built_in"><span class="hljs-built_in">Public</span></span> Sub EraseLabel() <span class="hljs-keyword"><span class="hljs-keyword">If</span></span> wList IsNot <span class="hljs-keyword"><span class="hljs-keyword">Nothing</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Then</span></span> wList.<span class="hljs-keyword"><span class="hljs-keyword">ForEach</span></span>(Sub(obj) obj.EraseLebel()) <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> Sub <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Class</span></span></code> </pre><br></div></div><br><pre> <code class="hljs pgsql"> &lt;CommandMethod("CrMyCircle")&gt; _ <span class="hljs-built_in"><span class="hljs-built_in">Public</span></span> Sub CrMyCircle() <span class="hljs-keyword"><span class="hljs-keyword">If</span></span> wList <span class="hljs-keyword"><span class="hljs-keyword">Is</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Nothing</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Then</span></span> wList = <span class="hljs-built_in"><span class="hljs-built_in">New</span></span> List(<span class="hljs-keyword"><span class="hljs-keyword">Of</span></span> MyCircle) Dim acDoc <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> AppServ.Document = AppServ.Application.DocumentManager.MdiActiveDocument Dim acCurDb <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Database</span></span> = acDoc.<span class="hljs-keyword"><span class="hljs-keyword">Database</span></span> Dim pPtRes <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> PromptPointResult = acDoc.Editor.GetPoint(" : ") <span class="hljs-keyword"><span class="hljs-keyword">If</span></span> (pPtRes.Status = PromptStatus.OK) <span class="hljs-keyword"><span class="hljs-keyword">Then</span></span> Dim wPrmtDistOpt <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> <span class="hljs-built_in"><span class="hljs-built_in">New</span></span> PromptDistanceOptions(" : ") wPrmtDistOpt.BasePoint = pPtRes.<span class="hljs-keyword"><span class="hljs-keyword">Value</span></span> wPrmtDistOpt.UseBasePoint = <span class="hljs-keyword"><span class="hljs-keyword">True</span></span> Dim pDistRes <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> PromptDoubleResult = acDoc.Editor.GetDistance(wPrmtDistOpt) <span class="hljs-keyword"><span class="hljs-keyword">If</span></span> (pDistRes.Status = PromptStatus.OK) <span class="hljs-keyword"><span class="hljs-keyword">Then</span></span> wList.<span class="hljs-keyword"><span class="hljs-keyword">Add</span></span>(<span class="hljs-built_in"><span class="hljs-built_in">New</span></span> MyCircle(pPtRes.<span class="hljs-keyword"><span class="hljs-keyword">Value</span></span>, pDistRes.<span class="hljs-keyword"><span class="hljs-keyword">Value</span></span>, acCurDb)) <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> <span class="hljs-keyword"><span class="hljs-keyword">If</span></span> <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> <span class="hljs-keyword"><span class="hljs-keyword">If</span></span> <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> Sub</code> </pre><br>  The CrMyCircle command draws our objects. <br><br><pre> <code class="hljs vbscript"> &lt;CommandMethod(<span class="hljs-string"><span class="hljs-string">"SaveToXML"</span></span>)&gt; _ <span class="hljs-keyword"><span class="hljs-keyword">Public</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Sub</span></span> SaveToXML() <span class="hljs-keyword"><span class="hljs-keyword">Dim</span></span> nDialog As <span class="hljs-keyword"><span class="hljs-keyword">New</span></span> SaveFileDialog nDialog.<span class="hljs-built_in"><span class="hljs-built_in">Filter</span></span> = <span class="hljs-string"><span class="hljs-string">"XML|*.xml"</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Dim</span></span> wDoc As <span class="hljs-keyword"><span class="hljs-keyword">New</span></span> XmlDocument wDoc.LoadXml(<span class="hljs-string"><span class="hljs-string">"&lt;?xml version=""1.0"" encoding=""utf-8""?&gt;&lt;MyCircleList/&gt;"</span></span>) <span class="hljs-keyword"><span class="hljs-keyword">If</span></span> wList IsNot <span class="hljs-literal"><span class="hljs-literal">Nothing</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Then</span></span> wList.ForEach(<span class="hljs-keyword"><span class="hljs-keyword">Sub</span></span>(obj) wDoc.DocumentElement.AppendChild(obj.ToXML(wDoc))) <span class="hljs-keyword"><span class="hljs-keyword">If</span></span> nDialog.ShowDialog = DialogResult.OK <span class="hljs-keyword"><span class="hljs-keyword">Then</span></span> wDoc.Save(nDialog.FileName) <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> <span class="hljs-keyword"><span class="hljs-keyword">If</span></span> <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Sub</span></span></code> </pre><br>  Save to XML. <br><br><pre> <code class="hljs pgsql"> &lt;CommandMethod("LoadFromXML")&gt; _ <span class="hljs-built_in"><span class="hljs-built_in">Public</span></span> Sub LoadFromXML() Dim nDialog <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> <span class="hljs-built_in"><span class="hljs-built_in">New</span></span> OpenFileDialog nDialog.<span class="hljs-keyword"><span class="hljs-keyword">Filter</span></span> = "XML|*.xml" Dim wDoc <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> <span class="hljs-built_in"><span class="hljs-built_in">New</span></span> XmlDocument Dim done <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> <span class="hljs-type"><span class="hljs-type">Boolean</span></span> = <span class="hljs-keyword"><span class="hljs-keyword">False</span></span> <span class="hljs-keyword"><span class="hljs-keyword">If</span></span> nDialog.ShowDialog = DialogResult.OK <span class="hljs-keyword"><span class="hljs-keyword">Then</span></span> wDoc.<span class="hljs-keyword"><span class="hljs-keyword">Load</span></span>(nDialog.FileName) done = <span class="hljs-keyword"><span class="hljs-keyword">True</span></span> <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> <span class="hljs-keyword"><span class="hljs-keyword">If</span></span> <span class="hljs-keyword"><span class="hljs-keyword">If</span></span> done <span class="hljs-keyword"><span class="hljs-keyword">Then</span></span> <span class="hljs-keyword"><span class="hljs-keyword">If</span></span> wList <span class="hljs-keyword"><span class="hljs-keyword">Is</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Nothing</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Then</span></span> wList = <span class="hljs-built_in"><span class="hljs-built_in">New</span></span> List(<span class="hljs-keyword"><span class="hljs-keyword">Of</span></span> MyCircle) Dim acDoc <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> AppServ.Document = AppServ.Application.DocumentManager.MdiActiveDocument Dim acCurDb <span class="hljs-keyword"><span class="hljs-keyword">As</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Database</span></span> = acDoc.<span class="hljs-keyword"><span class="hljs-keyword">Database</span></span> <span class="hljs-keyword"><span class="hljs-keyword">For</span></span> <span class="hljs-keyword"><span class="hljs-keyword">Each</span></span> ch <span class="hljs-keyword"><span class="hljs-keyword">In</span></span> wDoc.DocumentElement.ChildNodes wList.<span class="hljs-keyword"><span class="hljs-keyword">Add</span></span>(<span class="hljs-built_in"><span class="hljs-built_in">New</span></span> MyCircle(ch, acCurDb)) Next <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> <span class="hljs-keyword"><span class="hljs-keyword">If</span></span> <span class="hljs-keyword"><span class="hljs-keyword">End</span></span> Sub</code> </pre><br>  Load from XML. <br><br><h5>  Conclusion </h5><br>  Just like that, it is not easy to create a class that is able to associate drawing data with data from an external source (XML).  It is quite easy to modify it, for interacting with an external database. </div><p>Source: <a href="https://habr.com/ru/post/271109/">https://habr.com/ru/post/271109/</a></p>
<section class="more-articles-navigation-panel js-more-articles-navigation-panel">
<h4>More articles:</h4>
<nav class="list-of-articles-container js-list-of-articles-container"><ul class="list-of-pages js-list-of-pages">
<li><a href="../271099/index.html">Innovative Forum for development companies in Minsk</a></li>
<li><a href="../271101/index.html">Something "steals" disk space?</a></li>
<li><a href="../271103/index.html">Paul Graham: "Revenge of the nerds", part 3</a></li>
<li><a href="../271105/index.html">Another way to implement binding computable properties in WPF</a></li>
<li><a href="../271107/index.html">High Flight Frames - Cloud HR and Big Data</a></li>
<li><a href="../271111/index.html">AllcountJS and ionic: Mobile application for CRM in 30 minutes</a></li>
<li><a href="../271113/index.html">Two-factor authentication of AnyConnect clients. Active Directory and Azure Multi-Factor Authentication Server</a></li>
<li><a href="../271115/index.html">Hibernate. Basic principles of working with sessions and transactions</a></li>
<li><a href="../271117/index.html">Hammer on the ORM</a></li>
<li><a href="../271119/index.html">Microsoft boosts Edge web browser security</a></li>
</ul></nav>
</section><br />
<a href="../../allArticles.html"><strong>All Articles</strong></a>
<script src="../../js/main.js"></script>

<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
  (function (d, w, c) {
      (w[c] = w[c] || []).push(function() {
          try {
              w.yaCounter52496797 = new Ya.Metrika({
                  id:52496797,
                  clickmap:true,
                  trackLinks:true,
                  accurateTrackBounce:true,
                  webvisor:true
              });
          } catch(e) { }
      });

      var n = d.getElementsByTagName("script")[0],
          s = d.createElement("script"),
          f = function () { n.parentNode.insertBefore(s, n); };
      s.type = "text/javascript";
      s.async = true;
      s.src = "https://mc.yandex.ru/metrika/watch.js";

      if (w.opera == "[object Opera]") {
          d.addEventListener("DOMContentLoaded", f, false);
      } else { f(); }
  })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/52496797" style="position:absolute; left:-9999px;" alt="" /></div></noscript>

<!-- Google Analytics -->
  <script>
    window.ga = function () { ga.q.push(arguments) }; ga.q = []; ga.l = +new Date;
    ga('create', 'UA-134931760-1', 'auto'); ga('send', 'pageview')
  </script>
  <script src="https://www.google-analytics.com/analytics.js" async defer></script>

</section>

  <footer class="page-footer">
    <div class="page-footer-legal-info-container page-footer-element">
      <p>
        Weekly-Geekly | <span class="page-footer-legal-info-year js-page-footer-legal-info-year">2019</span>
      </p>
    </div>
    <div class="page-footer-counters-container page-footer-element">
      <a class="page-footer-counter-clustrmap" href='#'  title='Visit tracker'><img src='https://clustrmaps.com/map_v2.png?cl=698e5a&w=271&t=t&d=6iCFw7uJz0zcOaoxz5k5PcLCJUzv2WG8G5V8M3U6Rc4&co=3a3a3a&ct=ffffff'/></a>
    </div>
  </footer>
</body>

</html>