<!doctype html>
<html class="no-js" lang="en">

<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-134931760-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-134931760-1');
  </script>

  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Creating plug-ins for AutoCAD using the .NET API (part 4 - inserting primitive objects)</title>
  <link rel="icon" type="image/x-icon" href="/favicon.ico" />
  <meta name="description" content="Welcome to the fourth part of the development cycle for plug-ins for AutoCAD. The previous articles dealt with general issues of creating a plug-in - ...">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="../../css/main.css">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="../../js/vendors/jquery-3.3.1.min.js"><\/script>')</script>

  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <script>
       (adsbygoogle = window.adsbygoogle || []).push({
            google_ad_client: "ca-pub-6974184241884155",
            enable_page_level_ads: true
       });
  </script>
</head>

<body>
  <!--[if lte IE 9]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
  <![endif]-->
  <header class="page-header js-page-header">
    <a class="page-header-logo-container" href="https://weekly-geekly.github.io/index.html"></a>
    <div class="page-header-text">Geekly Articles each Day</div>
  </header>
  <nav class="page-headings-container js-page-headings-container"></nav>
  <div class="tools-bar js-tools-bar">
    <!-- <a href="../../search.html" title="Search">üîé</a> -->
    <a class="js-list-of-headings-button" data-state="closed" href="#" title="Headings">üìú</a>
    <a class="js-go-to-top-button" href="#" title="Go to Top">‚¨ÜÔ∏è</a>
    <a class="js-go-to-bottom-button" href="#" title="Go to Bottom">‚¨áÔ∏è</a>
  </div>
  <a href="http://bit.ly/donateToWeeklyGeekly" class="donate-btn">DONATE</a>
  <section class="page js-page"><h1>Creating plug-ins for AutoCAD using the .NET API (part 4 - inserting primitive objects)</h1><div class="post__text post__text-html js-mediator-article">  Welcome to the fourth part <a href="http://habrahabr.ru/post/235723/"><u>of the</u></a> development <a href="http://habrahabr.ru/post/235723/"><u>cycle</u></a> for plug-ins for AutoCAD.  The previous articles dealt with general issues of creating a plug-in - and now, armed with this knowledge, you can finally move on to the main task facing the AutoCAD user: drawing editing. <br><br>  In this article, the simplest operations that a developer may require are: creating and placing graphic primitives on a drawing (line, polyline, circle, ellipse, and circle). <br><br><pre><code class="hljs cs"><span class="hljs-keyword"><span class="hljs-keyword">public</span></span> <span class="hljs-keyword"><span class="hljs-keyword">static</span></span> <span class="hljs-keyword"><span class="hljs-keyword">string</span></span> disclaimer = <span class="hljs-string"><span class="hljs-string">"          AutoCAD.   ‚Äì      ."</span></span>;</code> </pre> <a name="habracut"></a><br><h1>  Before work </h1><br>  If a dear reader wants to repeat the examples presented on his computer, then to simplify life, it is worth exploring autoloading plugins.  For example, you can read the <a href="http://habrahabr.ru/post/148844/"><u>post</u></a> <a href="https://habrahabr.ru/users/namolem/" class="user_link">Namolem</a> - there is a mention of this. 
      <br>
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <ins class="adsbygoogle"
          style="display:block; text-align:center;"
          data-ad-layout="in-article"
          data-ad-format="fluid"
          data-ad-client="ca-pub-6974184241884155"
          data-ad-slot="8945601208"></ins>
        <script>
          (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
      <br>
      Summarize the essence of the problem: since after loading the plugin it is impossible to ‚Äúunload‚Äù it, the only way to launch the plugin whose code has been changed is to close AutoCAD, then launch it again and reload the plugin.  This trivial operation takes a couple of minutes on the force, but after fifty or one hundred repetitions, it begins to annoy wildly, I would even say - <i>enrage</i> . <br><br>  The autoload of the plug-in allows you to exclude one of the stages of this procedure, which will help to save a couple of <s>thousand</s> nerve cells. <br><br><h1>  Line </h1><br>  Adding a line to a drawing is easy.  Let's do this by using as an example the example set out in the <a href="http://help.autodesk.com/view/ACD/2016/ENU/%3Fguid%3DGUID-47E8A12E-2ED4-4E78-ADA3-AAC9B4223C3C"><u>documentation</u></a> ( <a href="https://sites.google.com/site/bushmansnetlaboratory/translate-manual/sozdanie-i-redaktirovanie-obektov-autocad/sozdanie-obektov/sozdanie-otrezkov/sozdanie-otrezka-line"><u>translation</u></a> ). <br><br><div class="spoiler">  <b class="spoiler_title">Plugin code:</b> <div class="spoiler_text"><pre> <code class="hljs pgsql"><span class="hljs-keyword"><span class="hljs-keyword">using</span></span> <span class="hljs-keyword"><span class="hljs-keyword">System</span></span>; <span class="hljs-keyword"><span class="hljs-keyword">using</span></span> <span class="hljs-keyword"><span class="hljs-keyword">System</span></span>.IO; <span class="hljs-keyword"><span class="hljs-keyword">using</span></span> Autodesk.AutoCAD.Runtime; <span class="hljs-keyword"><span class="hljs-keyword">using</span></span> Autodesk.AutoCAD.DatabaseServices; <span class="hljs-keyword"><span class="hljs-keyword">using</span></span> Autodesk.AutoCAD.Geometry; <span class="hljs-keyword"><span class="hljs-keyword">using</span></span> Autodesk.AutoCAD.ApplicationServices; <span class="hljs-keyword"><span class="hljs-keyword">using</span></span> acad = Autodesk.AutoCAD.ApplicationServices.Application; namespace HabrPlug_Primitives { <span class="hljs-built_in"><span class="hljs-built_in">public</span></span> <span class="hljs-keyword"><span class="hljs-keyword">class</span></span> ClassMyAutoCADDLL { <span class="hljs-built_in"><span class="hljs-built_in">public</span></span> <span class="hljs-keyword"><span class="hljs-keyword">class</span></span> Commands : IExtensionApplication { //        AutoCAD  "HabrCommand" [CommandMethod("HabrCommand")] <span class="hljs-built_in"><span class="hljs-built_in">public</span></span> <span class="hljs-type"><span class="hljs-type">void</span></span> HabrCommand() { //       Document acDoc = acad.DocumentManager.MdiActiveDocument; <span class="hljs-keyword"><span class="hljs-keyword">Database</span></span> acCurDb = acDoc.<span class="hljs-keyword"><span class="hljs-keyword">Database</span></span>; //   <span class="hljs-keyword"><span class="hljs-keyword">using</span></span> (<span class="hljs-keyword"><span class="hljs-keyword">Transaction</span></span> acTrans = acCurDb.TransactionManager.StartTransaction()) { //     BlockTable acBlkTbl; acBlkTbl = acTrans.GetObject(acCurDb.BlockTableId, OpenMode.ForRead) <span class="hljs-keyword"><span class="hljs-keyword">as</span></span> BlockTable; //    (Model Space) -          BlockTableRecord acBlkTblRec; acBlkTblRec = acTrans.GetObject(acBlkTbl[BlockTableRecord.ModelSpace], OpenMode.ForWrite) <span class="hljs-keyword"><span class="hljs-keyword">as</span></span> BlockTableRecord; //        <span class="hljs-type"><span class="hljs-type">Line</span></span> acLine = <span class="hljs-built_in"><span class="hljs-built_in">new</span></span> Line(<span class="hljs-built_in"><span class="hljs-built_in">new</span></span> Point3d(<span class="hljs-number"><span class="hljs-number">25</span></span>, <span class="hljs-number"><span class="hljs-number">25</span></span>, <span class="hljs-number"><span class="hljs-number">0</span></span>), <span class="hljs-built_in"><span class="hljs-built_in">new</span></span> Point3d(<span class="hljs-number"><span class="hljs-number">33</span></span>, <span class="hljs-number"><span class="hljs-number">33</span></span>, <span class="hljs-number"><span class="hljs-number">0</span></span>)); //         acLine.SetDatabaseDefaults(); //       acBlkTblRec.AppendEntity(acLine); //       acTrans.AddNewlyCreatedDBObject(acLine, <span class="hljs-keyword"><span class="hljs-keyword">true</span></span>); //   acTrans.<span class="hljs-keyword"><span class="hljs-keyword">Commit</span></span>(); } } //  Initialize()  Terminate() ,    IExtensionApplication <span class="hljs-built_in"><span class="hljs-built_in">public</span></span> <span class="hljs-type"><span class="hljs-type">void</span></span> Initialize() { } <span class="hljs-built_in"><span class="hljs-built_in">public</span></span> <span class="hljs-type"><span class="hljs-type">void</span></span> Terminate() { } } } }</code> </pre></div></div><br><div class="spoiler">  <b class="spoiler_title">When creating a project, of course, do not forget about all sorts of stuff ...)</b> <div class="spoiler_text">  First, you need to specify the required version of the .NET Framework (in my case it is .NET Framework 3.5). <br><br>  Secondly, you need to add links to <b>AcDbMgd.dll</b> and <b>AcMgd.dll libraries</b> and in the properties of these links to prevent copying of libraries to the target folder of the project (set the <code>CopyLocal</code> parameter to <code>False</code> ). <br></div></div><br>  The code itself is extremely simple, there is nothing special to describe in detail here. <br><br>  <u>First</u> , we start a transaction (what it is and why it is needed, was discussed in the last article). <br><br>  <u>Secondly</u> , we open the model space ( <code>Model Space</code> ) - this is, in fact, our drawing.  A clearer definition of Model Space can be found <a href="https://sites.google.com/site/bushmansnetlaboratory/translate-manual/opredelenie-sloeev-i-pecat/prostranstvo-modeli-model-space-i-prostranstvo-lista-paper-space"><u>here</u></a> and <a href="http://help.autodesk.com/view/ACD/2016/ENU/%3Fguid%3DGUID-2A6032EE-58D5-49DB-B7CD-3778A5CFEE0B"><u>there</u></a> .  Since we are going to add a new object to the drawing, we need to request read and write access ( <code>OpenMode.ForWrite</code> ). <br><br>  <u>Third</u> , we create a graphic object (in our case, a line), specifying the necessary parameters in the constructor (in our case, the starting and ending points). <br><br>  <u>Fourth</u> , we must set all properties for the object.  In this example, we set default values ‚Äã‚Äãfor all properties by calling the <code>SetDatabaseDefaults()</code> function to do this.  A mean male description of this function can be found in the <a href="http://docs.autodesk.com/ACDMAC/2013/ENU/ObjectARX%2520Reference/index.html%3Ffrmname%3Dtopic%26frmfile%3D!!OVERLOADED_setDatabaseDefaults_AcDbEntity.html"><u>ObjectARX Reference</u></a> . <br><div class="spoiler">  <b class="spoiler_title">Nb:</b> <div class="spoiler_text">  in practice, for simple cases, the call of this function can be neglected, however, it is <a href="http://forums.autodesk.com/t5/net/when-do-we-need-to-use-setdatabasedefaults/td-p/4370846"><u>believed</u></a> that it is better not to do so. <br></div></div><br>  <u>Fifthly</u> , it is necessary to add the created object to the model space (in other words, to the drawing).  This is done using the <code>AppendEntity()</code> function. <br><br>  <u>Sixthly</u> , it is necessary to add the created object to the transaction within which we work.  To do this, use the <code>AddNewlyCreatedDBObject()</code> function, which was already discussed in the previous article. <br><br>  <u>Finally</u> , after performing all the operations we need, we must commit the transaction by calling the <code>Commit()</code> method. <br><br>  After compiling the project, launch AutoCAD, load our plugin and execute the <b>HabrCommand</b> command.  The result is simple - but, I hope, it is understandable and predictable. <br><br><img src="https://habrastorage.org/files/ba0/657/33f/ba065733f6df4385be20ef564af4538b.png"><br><br>  If, after launching the command, the line on the screen did not appear - do not rush to get upset.  Instead, make sure that the center of coordinates - the point (0; 0) - is within the visible work area.  In addition, it makes sense to change the scale by turning the mouse wheel. <br><br>  For novice users of AutoCAD, it may come as a surprise that the scaling of the drawing occurs within certain limits.  Simply put, it is impossible to go from a scale of 1000% to a scale of 1% on the move - after a couple of mouse wheel scrolls, the scale will ‚Äúrest‚Äù on an invisible limiter.  To continue drawing scaling, you must run the <b>REGEN</b> command in the AutoCAD command line. <br><div class="spoiler">  <b class="spoiler_title">Nb:</b> <div class="spoiler_text">  from personal experience: if the <s>programmer completely stumbled, and it is already</s> incomprehensible what objects are created and whether they are created at all, you can open a clean drawing, execute an interesting piece of code on it and select all objects in the drawing by pressing the key combination ‚ÄúCtrl + A‚Äù.  After that, to find the created objects, as a rule, is not difficult. <br><br>  Let's refresh by example. <br><div class="spoiler">  <b class="spoiler_title">Picture TO:</b> <div class="spoiler_text"><img src="https://habrastorage.org/files/15b/df9/e7b/15bdf9e7b77e48359eaa639621b53f10.png"><br>  Well, where is the line here?) <br></div></div><div class="spoiler">  <b class="spoiler_title">Painting AFTER:</b> <div class="spoiler_text"><img src="https://habrastorage.org/files/c01/6bf/dfc/c016bfdfc81e4aa684f0d85ca02b59c0.png"><br>  The line with the head pretended by a speck of dust on the monitor gives out a blue small square and the appeared object properties window. <br></div></div></div></div><br><h1>  Polyline </h1><br>  Again, an example is in the <a href="http://help.autodesk.com/view/ACD/2016/ENU/%3Fguid%3DGUID-EC036F5A-1F02-40D3-B348-4193BA58CF0C"><u>documentation</u></a> ( <a href="https://sites.google.com/site/bushmansnetlaboratory/translate-manual/sozdanie-i-redaktirovanie-obektov-autocad/sozdanie-obektov/sozdanie-otrezkov/sozdanie-polilinii-polyline"><u>translation</u></a> ). <br><br><div class="spoiler">  <b class="spoiler_title">Command Code:</b> <div class="spoiler_text"><pre> <code class="hljs pgsql">[CommandMethod("HabrCommand")] <span class="hljs-built_in"><span class="hljs-built_in">public</span></span> <span class="hljs-type"><span class="hljs-type">void</span></span> HabrCommand() { //       Document acDoc = acad.DocumentManager.MdiActiveDocument; <span class="hljs-keyword"><span class="hljs-keyword">Database</span></span> acCurDb = acDoc.<span class="hljs-keyword"><span class="hljs-keyword">Database</span></span>; //   <span class="hljs-keyword"><span class="hljs-keyword">using</span></span> (<span class="hljs-keyword"><span class="hljs-keyword">Transaction</span></span> acTrans = acCurDb.TransactionManager.StartTransaction()) { //     BlockTable acBlkTbl; acBlkTbl = acTrans.GetObject(acCurDb.BlockTableId, OpenMode.ForRead) <span class="hljs-keyword"><span class="hljs-keyword">as</span></span> BlockTable; //    (Model Space) -          BlockTableRecord acBlkTblRec; acBlkTblRec = acTrans.GetObject(acBlkTbl[BlockTableRecord.ModelSpace], OpenMode.ForWrite) <span class="hljs-keyword"><span class="hljs-keyword">as</span></span> BlockTableRecord; //   Polyline acPolyline = <span class="hljs-built_in"><span class="hljs-built_in">new</span></span> Polyline(); //         acPolyline.SetDatabaseDefaults(); //     acPolyline.AddVertexAt(<span class="hljs-number"><span class="hljs-number">0</span></span>, <span class="hljs-built_in"><span class="hljs-built_in">new</span></span> Point2d(<span class="hljs-number"><span class="hljs-number">2</span></span>, <span class="hljs-number"><span class="hljs-number">4</span></span>), <span class="hljs-number"><span class="hljs-number">0</span></span>, <span class="hljs-number"><span class="hljs-number">0</span></span>, <span class="hljs-number"><span class="hljs-number">0</span></span>); acPolyline.AddVertexAt(<span class="hljs-number"><span class="hljs-number">1</span></span>, <span class="hljs-built_in"><span class="hljs-built_in">new</span></span> Point2d(<span class="hljs-number"><span class="hljs-number">4</span></span>, <span class="hljs-number"><span class="hljs-number">8</span></span>), <span class="hljs-number"><span class="hljs-number">0</span></span>, <span class="hljs-number"><span class="hljs-number">0</span></span>, <span class="hljs-number"><span class="hljs-number">0</span></span>); acPolyline.AddVertexAt(<span class="hljs-number"><span class="hljs-number">2</span></span>, <span class="hljs-built_in"><span class="hljs-built_in">new</span></span> Point2d(<span class="hljs-number"><span class="hljs-number">6</span></span>, <span class="hljs-number"><span class="hljs-number">6</span></span>), <span class="hljs-number"><span class="hljs-number">0</span></span>, <span class="hljs-number"><span class="hljs-number">0</span></span>, <span class="hljs-number"><span class="hljs-number">0</span></span>); acPolyline.AddVertexAt(<span class="hljs-number"><span class="hljs-number">3</span></span>, <span class="hljs-built_in"><span class="hljs-built_in">new</span></span> Point2d(<span class="hljs-number"><span class="hljs-number">8</span></span>, <span class="hljs-number"><span class="hljs-number">11</span></span>), <span class="hljs-number"><span class="hljs-number">0</span></span>, <span class="hljs-number"><span class="hljs-number">0</span></span>, <span class="hljs-number"><span class="hljs-number">0</span></span>); //       acBlkTblRec.AppendEntity(acPolyline); //       acTrans.AddNewlyCreatedDBObject(acPolyline, <span class="hljs-keyword"><span class="hljs-keyword">true</span></span>); //   acTrans.<span class="hljs-keyword"><span class="hljs-keyword">Commit</span></span>(); } }</code> </pre></div></div><br>  Result: <br><br><img src="https://habrastorage.org/files/683/bc9/a86/683bc9a8647746a8babebd201c6f69cb.png"><br><br>  There is nothing to clarify here.  If desired, by adding new points a polyline can be turned into a <s>trolleybus of a</s> rather complex geometric shape - for example, an asterisk ... <br><div class="spoiler">  <b class="spoiler_title">... or is it a trolley bus?</b> <div class="spoiler_text"><pre> <code class="cs hljs">[<span class="hljs-meta"><span class="hljs-meta">CommandMethod(</span><span class="hljs-meta-string"><span class="hljs-meta"><span class="hljs-meta-string">"HabrCommand"</span></span></span><span class="hljs-meta">)</span></span>] <span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">public</span></span></span><span class="hljs-function"> </span><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">void</span></span></span><span class="hljs-function"> </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">HabrCommand</span></span></span><span class="hljs-function">(</span><span class="hljs-params"></span><span class="hljs-function"><span class="hljs-params"></span>)</span></span> { <span class="hljs-comment"><span class="hljs-comment">//       Document acDoc = acad.DocumentManager.MdiActiveDocument; Database acCurDb = acDoc.Database; //   using (Transaction acTrans = acCurDb.TransactionManager.StartTransaction()) { //     BlockTable acBlkTbl; acBlkTbl = acTrans.GetObject(acCurDb.BlockTableId, OpenMode.ForRead) as BlockTable; //    (Model Space) -          BlockTableRecord acBlkTblRec; acBlkTblRec = acTrans.GetObject(acBlkTbl[BlockTableRecord.ModelSpace], OpenMode.ForWrite) as BlockTableRecord; //   Polyline acPolyline = new Polyline(); //         acPolyline.SetDatabaseDefaults(); //     acPolyline.AddVertexAt(0, new Point2d(100, 100), 0, 0, 0); acPolyline.AddVertexAt(1, new Point2d(100, 650), 0, 0, 0); acPolyline.AddVertexAt(2, new Point2d(1050, 650), 0, 0, 0); acPolyline.AddVertexAt(3, new Point2d(650, 1150), 0, 0, 0); acPolyline.AddVertexAt(4, new Point2d(1050, 650), 0, 0, 0); acPolyline.AddVertexAt(5, new Point2d(2050, 650), 0, 0, 0); acPolyline.AddVertexAt(6, new Point2d(2050, 100), 0, 0, 0); acPolyline.AddVertexAt(7, new Point2d(1950, 100), 0, 0, 0); acPolyline.AddVertexAt(8, new Point2d(1950, 400), 0, 0, 0); acPolyline.AddVertexAt(9, new Point2d(1800, 400), 0, 0, 0); acPolyline.AddVertexAt(10, new Point2d(1800, 100), 0, 0, 0); acPolyline.AddVertexAt(11, new Point2d(1950, 100), 0, 0, 0); acPolyline.AddVertexAt(12, new Point2d(1700, 100), 0, 0, 0); acPolyline.AddVertexAt(13, new Point2d(1660, 170), 0, 0, 0); acPolyline.AddVertexAt(14, new Point2d(1600, 225), 0, 0, 0); acPolyline.AddVertexAt(15, new Point2d(1500, 225), 0, 0, 0); acPolyline.AddVertexAt(16, new Point2d(1440, 170), 0, 0, 0); acPolyline.AddVertexAt(17, new Point2d(1400, 100), 0, 0, 0); acPolyline.AddVertexAt(18, new Point2d(850, 100), 0, 0, 0); acPolyline.AddVertexAt(19, new Point2d(1200, 100), 0, 0, 0); acPolyline.AddVertexAt(20, new Point2d(1200, 400), 0, 0, 0); acPolyline.AddVertexAt(21, new Point2d(1000, 400), 0, 0, 0); acPolyline.AddVertexAt(22, new Point2d(1000, 100), 0, 0, 0); acPolyline.AddVertexAt(23, new Point2d(1100, 100), 0, 0, 0); acPolyline.AddVertexAt(24, new Point2d(1100, 400), 0, 0, 0); acPolyline.AddVertexAt(25, new Point2d(1100, 100), 0, 0, 0); acPolyline.AddVertexAt(26, new Point2d(850, 100), 0, 0, 0); acPolyline.AddVertexAt(27, new Point2d(810, 170), 0, 0, 0); acPolyline.AddVertexAt(28, new Point2d(750, 225), 0, 0, 0); acPolyline.AddVertexAt(29, new Point2d(650, 225), 0, 0, 0); acPolyline.AddVertexAt(30, new Point2d(590, 170), 0, 0, 0); acPolyline.AddVertexAt(31, new Point2d(550, 100), 0, 0, 0); acPolyline.AddVertexAt(32, new Point2d(100, 100), 0, 0, 0); acPolyline.AddVertexAt(33, new Point2d(450, 100), 0, 0, 0); acPolyline.AddVertexAt(34, new Point2d(450, 400), 0, 0, 0); acPolyline.AddVertexAt(35, new Point2d(250, 400), 0, 0, 0); acPolyline.AddVertexAt(36, new Point2d(250, 100), 0, 0, 0); acPolyline.AddVertexAt(37, new Point2d(350, 100), 0, 0, 0); acPolyline.AddVertexAt(38, new Point2d(350, 400), 0, 0, 0); //       acBlkTblRec.AppendEntity(acPolyline); //       acTrans.AddNewlyCreatedDBObject(acPolyline, true); //   acTrans.Commit(); } }</span></span></code> </pre><br><img src="https://habrastorage.org/files/4a4/eaa/fc8/4a4eaafc82d8408eb3e47017564845f6.PNG"><br><br>  Yes, I also noticed that the trolley has no wheels.  But we still don‚Äôt know how to draw a circle, but square wheels ... No, let‚Äôs go better. <br></div></div><br><h1>  Circle </h1><br>  Consider an example of adding a circle to a drawing diligently reprinted from the documentation (links were above). <br><div class="spoiler">  <b class="spoiler_title">Command Code:</b> <div class="spoiler_text"><pre> <code class="hljs pgsql">[CommandMethod("HabrCommand")] <span class="hljs-built_in"><span class="hljs-built_in">public</span></span> <span class="hljs-type"><span class="hljs-type">void</span></span> HabrCommand() { //       Document acDoc = acad.DocumentManager.MdiActiveDocument; <span class="hljs-keyword"><span class="hljs-keyword">Database</span></span> acCurDb = acDoc.<span class="hljs-keyword"><span class="hljs-keyword">Database</span></span>; //   <span class="hljs-keyword"><span class="hljs-keyword">using</span></span> (<span class="hljs-keyword"><span class="hljs-keyword">Transaction</span></span> acTrans = acCurDb.TransactionManager.StartTransaction()) { //     BlockTable acBlkTbl; acBlkTbl = acTrans.GetObject(acCurDb.BlockTableId, OpenMode.ForRead) <span class="hljs-keyword"><span class="hljs-keyword">as</span></span> BlockTable; //    (Model Space) -          BlockTableRecord acBlkTblRec; acBlkTblRec = acTrans.GetObject(acBlkTbl[BlockTableRecord.ModelSpace], OpenMode.ForWrite) <span class="hljs-keyword"><span class="hljs-keyword">as</span></span> BlockTableRecord; //   <span class="hljs-type"><span class="hljs-type">Circle</span></span> acCircle = <span class="hljs-built_in"><span class="hljs-built_in">new</span></span> Circle(); //     acCircle.SetDatabaseDefaults(); acCircle.Center = <span class="hljs-built_in"><span class="hljs-built_in">new</span></span> Point3d(<span class="hljs-number"><span class="hljs-number">2.5</span></span>, <span class="hljs-number"><span class="hljs-number">3.14</span></span>, <span class="hljs-number"><span class="hljs-number">0</span></span>); acCircle.Radius = <span class="hljs-number"><span class="hljs-number">4.25</span></span>; //       acBlkTblRec.AppendEntity(acCircle); //       acTrans.AddNewlyCreatedDBObject(acCircle, <span class="hljs-keyword"><span class="hljs-keyword">true</span></span>); //   acTrans.<span class="hljs-keyword"><span class="hljs-keyword">Commit</span></span>(); } }</code> </pre></div></div><br>  There should be no difficulties with adding a circle to the drawing: all that is needed is to set the center and the radius. <br><br>  Result: <br><br><img src="https://habrastorage.org/files/826/4d5/fcc/8264d5fccaaf494897d45a92fa09a0fc.png"><br><br><div class="spoiler">  <b class="spoiler_title">Nb:</b> <div class="spoiler_text">  When working with indirect lines, it is worth remembering that in some cases they may not be displayed correctly on the screen. <br><br>  In particular, if in this example you execute the <b>HabrCommand</b> command with a large distance and then greatly increase the scale (to bring the elements of the drawing closer), then the effect shown in the picture below will be observed.  Those who often work with AutoCAD probably got used to this ‚Äî but for the first time I saw what my circle had become, I had been looking for a mistake in the code for a long time and had killed several hours trying to ‚Äúimprove the rendering accuracy‚Äù.) <br><br><img src="https://habrastorage.org/files/36f/164/ada/36f164adaef148218050a07934349f77.png"><br><br>  To restore the original shape of a circle, you can use the <b>REGEN</b> command in the AutoCAD command line: <br><br><img src="https://habrastorage.org/files/4bf/8a3/673/4bf8a367390f4f179655287c819ababd.png"><br><br>  Once again, I emphasize that this effect occurs exclusively when <i>displayed</i> .  Inside a document, a circle is always a circle, no matter who it looks like outside. <br></div></div><br><h1>  Ellipse </h1><br>  Creating an ellipse is somewhat different from creating a circle: its parameters must be explicitly specified in the constructor (details are given <a href="http://adndevblog.typepad.com/autocad/2012/05/creating-an-ellipse.html"><u>here</u></a> ). <br><br><div class="spoiler">  <b class="spoiler_title">Command Code:</b> <div class="spoiler_text"><pre> <code class="hljs pgsql">[CommandMethod("HabrCommand")] <span class="hljs-built_in"><span class="hljs-built_in">public</span></span> <span class="hljs-type"><span class="hljs-type">void</span></span> HabrCommand() { //       Document acDoc = acad.DocumentManager.MdiActiveDocument; <span class="hljs-keyword"><span class="hljs-keyword">Database</span></span> acCurDb = acDoc.<span class="hljs-keyword"><span class="hljs-keyword">Database</span></span>; //   <span class="hljs-keyword"><span class="hljs-keyword">using</span></span> (<span class="hljs-keyword"><span class="hljs-keyword">Transaction</span></span> acTrans = acCurDb.TransactionManager.StartTransaction()) { //     BlockTable acBlkTbl; acBlkTbl = acTrans.GetObject(acCurDb.BlockTableId, OpenMode.ForRead) <span class="hljs-keyword"><span class="hljs-keyword">as</span></span> BlockTable; //    (Model Space) -          BlockTableRecord acBlkTblRec; acBlkTblRec = acTrans.GetObject(acBlkTbl[BlockTableRecord.ModelSpace], OpenMode.ForWrite) <span class="hljs-keyword"><span class="hljs-keyword">as</span></span> BlockTableRecord; //    Point3d center = Point3d.Origin; Vector3d normal = Vector3d.ZAxis; Vector3d majorAxis = <span class="hljs-number"><span class="hljs-number">100</span></span> * Vector3d.XAxis; <span class="hljs-type"><span class="hljs-type">double</span></span> radiusRatio = <span class="hljs-number"><span class="hljs-number">0.5</span></span>; <span class="hljs-type"><span class="hljs-type">double</span></span> startAng = <span class="hljs-number"><span class="hljs-number">0.0</span></span>; <span class="hljs-type"><span class="hljs-type">double</span></span> endAng = Math.PI * <span class="hljs-number"><span class="hljs-number">2</span></span>; //  ,     Ellipse acEllipse = <span class="hljs-built_in"><span class="hljs-built_in">new</span></span> Ellipse(center, normal, majorAxis, radiusRatio, startAng, endAng); //       acBlkTblRec.AppendEntity(acEllipse); //       acTrans.AddNewlyCreatedDBObject(acEllipse, <span class="hljs-keyword"><span class="hljs-keyword">true</span></span>); //   acTrans.<span class="hljs-keyword"><span class="hljs-keyword">Commit</span></span>(); } }</code> </pre></div></div><br>  Result (blue line added for explanation): <br><br><img src="https://habrastorage.org/files/cde/2fb/66b/cde2fb66bd2443f38801eaef92f2bd54.png"><br><br>  When creating an ellipse, we set the following parameters to it: <br><ol><li>  The center (center) of the ellipse - this is all clear. </li><li>  Normal (normal) - a vector perpendicular to the plane of the ellipse.  As we add an object to the XY plane, the normal will be the Z axis. </li><li>  Major axis (majorAxis) - in terms of AutoCAD, is a vector with a length equal to half the ‚Äúwidth‚Äù of the ellipse (as the blue segment in the figure).  In ordinary mathematics, this is called the "big half".  In our example, we specified a vector of length 100, in the direction coinciding with the abscissa axis. </li><li>  Radius (radiusRatio) - determines how far the ellipse is.  In this example, the maximum coordinate of the ellipse along the Y axis will be 100 * 0.5 = 50. </li><li>  Start and end angles - define the start and end angles of the curves.  The principle is well explained by the picture below, which is taken <a href="http://knowledge.autodesk.com/support/autocad-utility-design/getting-started/caas/CloudHelp/cloudhelp/2016/PTB/AutoCAD-ActiveX/files/GUID-5F2762C5-A24D-4A35-92F3-AC31311BE503-htm.html"><u>from here</u></a> . <br><img src="https://habrastorage.org/files/fb1/08c/64b/fb108c64b6ad437397e7287e86914d46.png"><br></li></ol><br>  To draw the whole shape, you need to "run" a full circle, that is, 360 degrees, or 2pi (as in the polar coordinate system).  If we specify less, we get only part of the shape. <br><br><div class="spoiler">  <b class="spoiler_title">Another example of an ellipse.</b> <div class="spoiler_text">  Let's try to set an ellipse with new parameters: <br><pre> <code class="cs hljs">Point3d center = Point3d.Origin; Vector3d normal = Vector3d.ZAxis; Vector3d majorAxis = <span class="hljs-number"><span class="hljs-number">100</span></span> * Vector3d.XAxis + <span class="hljs-number"><span class="hljs-number">100</span></span> * Vector3d.YAxis; <span class="hljs-keyword"><span class="hljs-keyword">double</span></span> radiusRatio = <span class="hljs-number"><span class="hljs-number">0.5</span></span>; <span class="hljs-keyword"><span class="hljs-keyword">double</span></span> startAng = Math.PI * <span class="hljs-number"><span class="hljs-number">0.1</span></span>; <span class="hljs-keyword"><span class="hljs-keyword">double</span></span> endAng = Math.PI * <span class="hljs-number"><span class="hljs-number">1.3</span></span>; Ellipse acEllipse = <span class="hljs-keyword"><span class="hljs-keyword">new</span></span> Ellipse(center, normal, majorAxis, radiusRatio, startAng, endAng);</code> </pre><br>  We obtain the following (the line is drawn for easy orientation): <br><br><img src="https://habrastorage.org/files/cfa/b9b/ac3/cfab9bac399745f9bd0906383fda3aa3.PNG"><br><br>  Since <code>startAng</code> greater than zero, the upper part of the ellipse does not start from the axis, but a little further.  Since <code>endAng</code> doesn‚Äôt reach <code>endAng</code> much, the lower part of the ellipse ends much earlier than it should be. <br><br>  The slope is provided by setting the axis vector ( <code>majorAxis = 100 * Vector3d.XAxis + 100 * Vector3d.YAxis</code> ).  Since the X component of this vector is equal in absolute value to the Y component, we obtain a slope of 45 degrees. <br><br>  The length of the semi-axis can be calculated by the Pythagorean theorem: this is the square root of the sum of squares of the X and Y coordinates. By calculating the square root of 100 <sup>2</sup> + 100 <sup>2</sup> (total 20,000), we get about 141. The total length of the ellipse, respectively, will be approximately 282. <br></div></div><br><h1>  A circle </h1><br>  To create a circle, you can use the hatching - <code>Hatch</code> ( <a href="http://docs.autodesk.com/CIV3D/2014/RUS/index.html%3Furl%3DfilesACD/GUID-26CEE5F5-F141-4256-B652-859F5D1330B0.htm,topicNumber%3DACDd30e703757"><u>documentation</u></a> , <a href="https://sites.google.com/site/bushmansnetlaboratory/translate-manual/sozdanie-i-redaktirovanie-obektov-autocad/sozdanie-obektov/sozdanie-strihovok-hatches"><u>translation</u></a> ). <br><br>  The procedure will be as follows: <br><ol><li>  Create a hatch border.  Any closed curve can act as a border - in our case it will be a circle. </li><li>  We set the necessary properties for the border of the hatching. </li><li>  Add a hatch border to the drawing. </li><li>  Create an array of objects that will be the borders of the hatching, and add our border to it. </li><li>  Create a hatching. </li><li>  Add a hatch to the drawing. </li><li>  We set the necessary properties for hatching. </li></ol><br>  Steps popribilos, but they are all simple. <br><br><div class="spoiler">  <b class="spoiler_title">Command Code:</b> <div class="spoiler_text"><pre> <code class="hljs pgsql">[CommandMethod("HabrCommand")] <span class="hljs-built_in"><span class="hljs-built_in">public</span></span> <span class="hljs-type"><span class="hljs-type">void</span></span> HabrCommand() { //       Document acDoc = acad.DocumentManager.MdiActiveDocument; <span class="hljs-keyword"><span class="hljs-keyword">Database</span></span> acCurDb = acDoc.<span class="hljs-keyword"><span class="hljs-keyword">Database</span></span>; //   <span class="hljs-keyword"><span class="hljs-keyword">using</span></span> (<span class="hljs-keyword"><span class="hljs-keyword">Transaction</span></span> acTrans = acCurDb.TransactionManager.StartTransaction()) { //     BlockTable acBlkTbl; acBlkTbl = acTrans.GetObject(acCurDb.BlockTableId, OpenMode.ForRead) <span class="hljs-keyword"><span class="hljs-keyword">as</span></span> BlockTable; //    (Model Space) -          BlockTableRecord acBlkTblRec; acBlkTblRec = acTrans.GetObject(acBlkTbl[BlockTableRecord.ModelSpace], OpenMode.ForWrite) <span class="hljs-keyword"><span class="hljs-keyword">as</span></span> BlockTableRecord; // <span class="hljs-number"><span class="hljs-number">1</span></span>)   -   <span class="hljs-type"><span class="hljs-type">Circle</span></span> acCircle = <span class="hljs-built_in"><span class="hljs-built_in">new</span></span> Circle(); // <span class="hljs-number"><span class="hljs-number">2</span></span>)     acCircle.SetDatabaseDefaults(); acCircle.Center = <span class="hljs-built_in"><span class="hljs-built_in">new</span></span> Point3d(<span class="hljs-number"><span class="hljs-number">2.5</span></span>, <span class="hljs-number"><span class="hljs-number">3.14</span></span>, <span class="hljs-number"><span class="hljs-number">0</span></span>); acCircle.Radius = <span class="hljs-number"><span class="hljs-number">4.25</span></span>; // <span class="hljs-number"><span class="hljs-number">3</span></span>)           acBlkTblRec.AppendEntity(acCircle); acTrans.AddNewlyCreatedDBObject(acCircle, <span class="hljs-keyword"><span class="hljs-keyword">true</span></span>); // <span class="hljs-number"><span class="hljs-number">4</span></span>)       -  ObjectIdCollection acObjIdColl = <span class="hljs-built_in"><span class="hljs-built_in">new</span></span> ObjectIdCollection(); acObjIdColl.<span class="hljs-keyword"><span class="hljs-keyword">Add</span></span>(acCircle.ObjectId); // <span class="hljs-number"><span class="hljs-number">5</span></span>)   Hatch acHatch = <span class="hljs-built_in"><span class="hljs-built_in">new</span></span> Hatch(); // <span class="hljs-number"><span class="hljs-number">6</span></span>)          acBlkTblRec.AppendEntity(acHatch); acTrans.AddNewlyCreatedDBObject(acHatch, <span class="hljs-keyword"><span class="hljs-keyword">true</span></span>); // <span class="hljs-number"><span class="hljs-number">7</span></span>)    acHatch.SetDatabaseDefaults(); acHatch.SetHatchPattern(HatchPatternType.PreDefined, "SOLID"); acHatch.Color = Autodesk.AutoCAD.Colors.Color.FromRgb(<span class="hljs-number"><span class="hljs-number">0</span></span>, <span class="hljs-number"><span class="hljs-number">200</span></span>, <span class="hljs-number"><span class="hljs-number">0</span></span>); acHatch.Associative = <span class="hljs-keyword"><span class="hljs-keyword">true</span></span>; acHatch.AppendLoop(HatchLoopTypes.Outermost, acObjIdColl); acHatch.EvaluateHatch(<span class="hljs-keyword"><span class="hljs-keyword">true</span></span>); //   acTrans.<span class="hljs-keyword"><span class="hljs-keyword">Commit</span></span>(); } }</code> </pre></div></div><br>  Result: <br><br><img src="https://habrastorage.org/files/657/c7b/d75/657c7bd75305490aa1f5ff7751b8b10c.PNG"><br><br>  The part where we create the border of the hatching should not cause any problems - it‚Äôs just a circle that we created and placed on the drawing.  The part where the hatching is created and added to the drawing does not need any explanations either.  The part where we set the hatching parameters remains.  Let us dwell on it in more detail. <br><br>  First, we call the <code>setDatabaseDefaults()</code> function, which sets the hatching parameters to be the default parameters.  The purpose of this function was discussed in the first section. <br><br>  Then we specify the type of hatching using the <code>SetHatchPattern()</code> function.  In this case, we want to draw a normal circle, so we choose the type <code>SOLID</code> - ‚Äúsolid‚Äù. <br><div class="spoiler">  <b class="spoiler_title">Nb:</b> <div class="spoiler_text">  You can set a different type of hatching, in addition to solid.  Out of the box, AutoCAD provides dozens of shading patterns ‚Äî to find them out, just call the properties of the Hatch object: <br><br><img src="https://habrastorage.org/files/719/7ce/c2f/7197cec2fb1040f8a7a7c1c930849428.png"><br><br>  Instead of <code>SOLID</code> we could specify something else.  For example, specifying <code>HOUND</code> , we would get the following result: <br><br><img src="https://habrastorage.org/files/c50/300/4bd/c503004bd18b4a579c0a36cec6c4fdef.png"><br><br>  In addition to the standard hatching ( <code>HatchPatternType.PreDefined</code> ), you can use third-party ones that were previously connected to AutoCAD.  Here is a <a href="http://adndevblog.typepad.com/autocad/2013/04/einvalidinput-while-creating-hatch-with-customdefined-pattern.html"><u>link</u></a> to an example. <br></div></div><br>  After setting the type of hatching, I indicated its color (the <code>Color</code> property) using the <code>FromRgb(byte ref, byte blue, byte green)</code> function <code>FromRgb(byte ref, byte blue, byte green)</code> . <br><br>  Then the <code>Associative</code> property follows - it determines whether the hatching will change size when its borders are resized. <br><div class="spoiler">  <b class="spoiler_title">Illustration</b> <div class="spoiler_text">  Here is what happens with our example ( <code>Associative = true</code> ) as the hatching boundaries change: <br><br><img src="https://habrastorage.org/files/2b3/e4a/ff0/2b3e4aff08764a40ba705ee35c3ebc9f.png"><br><br>  The new radius of the circle - 5, the hatching stretched out under the new radius. <br><br>  Here is an example with <code>Associative = false</code> : <br><br><img src="https://habrastorage.org/files/4e5/961/ff5/4e5961ff568b451aabd2653e66af6bdb.png"><br><br></div></div><br>  The ‚ÄúDefine the Hatch Boundaries (.NET)‚Äù section of the <a href="http://docs.autodesk.com/CIV3D/2014/RUS/index.html%3Furl%3DfilesACD/GUID-26CEE5F5-F141-4256-B652-859F5D1330B0.htm,topicNumber%3DACDd30e703757"><u>documentation</u></a> ( <a href="https://sites.google.com/site/bushmansnetlaboratory/translate-manual/sozdanie-i-redaktirovanie-obektov-autocad/sozdanie-obektov/sozdanie-strihovok-hatches/opredelenie-granic-strihovki"><u>translation</u></a> ) states that the <code>Associative</code> property must be set after adding the shriches to the block table (that is, the model space) and before calling the <code>AppendLoop</code> method. <br><br>  The <code>AppendLoop</code> method allows <code>AppendLoop</code> to specify the external border of the hatching and takes two parameters as input: the type of the border and the array of border-hatch objects.  As the first parameter, we specified <code>HatchLoopTypes.Outermost</code> , thereby denoting that we want to set the outer boundary of the hatching.  As the second, we have specified the previously created array of border-hatch objects. <br><div class="spoiler">  <b class="spoiler_title">Nb:</b> <div class="spoiler_text">  if necessary, you can set several internal borders in addition to the external one and define the behavior of hatching when they are crossed.  Details are <a href="http://help.autodesk.com/view/ACD/2016/ENU/%3Fguid%3DGUID-89CAED67-B3A0-4045-9D8B-9034D67E8D91"><u>here</u></a> ;  I will limit myself to a simple example of such a figure. <br><br><img src="https://habrastorage.org/files/e0b/467/2b4/e0b4672b4c1a41ad89fe30d0681170f9.png"><br><br><div class="spoiler">  <b class="spoiler_title">Command Code:</b> <div class="spoiler_text"><pre> <code class="hljs pgsql">[CommandMethod("HabrCommand")] <span class="hljs-built_in"><span class="hljs-built_in">public</span></span> <span class="hljs-type"><span class="hljs-type">void</span></span> HabrCommand() { //       Document acDoc = acad.DocumentManager.MdiActiveDocument; <span class="hljs-keyword"><span class="hljs-keyword">Database</span></span> acCurDb = acDoc.<span class="hljs-keyword"><span class="hljs-keyword">Database</span></span>; //   <span class="hljs-keyword"><span class="hljs-keyword">using</span></span> (<span class="hljs-keyword"><span class="hljs-keyword">Transaction</span></span> acTrans = acCurDb.TransactionManager.StartTransaction()) { //     BlockTable acBlkTbl; acBlkTbl = acTrans.GetObject(acCurDb.BlockTableId, OpenMode.ForRead) <span class="hljs-keyword"><span class="hljs-keyword">as</span></span> BlockTable; //    (Model Space) -          BlockTableRecord acBlkTblRec; acBlkTblRec = acTrans.GetObject(acBlkTbl[BlockTableRecord.ModelSpace], OpenMode.ForWrite) <span class="hljs-keyword"><span class="hljs-keyword">as</span></span> BlockTableRecord; //    Polyline acPolyline = <span class="hljs-built_in"><span class="hljs-built_in">new</span></span> Polyline(); acPolyline.SetDatabaseDefaults(); acPolyline.AddVertexAt(<span class="hljs-number"><span class="hljs-number">0</span></span>, <span class="hljs-built_in"><span class="hljs-built_in">new</span></span> Point2d(<span class="hljs-number"><span class="hljs-number">50</span></span>, <span class="hljs-number"><span class="hljs-number">50</span></span>), <span class="hljs-number"><span class="hljs-number">0</span></span>, <span class="hljs-number"><span class="hljs-number">0</span></span>, <span class="hljs-number"><span class="hljs-number">0</span></span>); acPolyline.AddVertexAt(<span class="hljs-number"><span class="hljs-number">1</span></span>, <span class="hljs-built_in"><span class="hljs-built_in">new</span></span> Point2d(<span class="hljs-number"><span class="hljs-number">150</span></span>, <span class="hljs-number"><span class="hljs-number">285</span></span>), <span class="hljs-number"><span class="hljs-number">0</span></span>, <span class="hljs-number"><span class="hljs-number">0</span></span>, <span class="hljs-number"><span class="hljs-number">0</span></span>); acPolyline.AddVertexAt(<span class="hljs-number"><span class="hljs-number">2</span></span>, <span class="hljs-built_in"><span class="hljs-built_in">new</span></span> Point2d(<span class="hljs-number"><span class="hljs-number">250</span></span>, <span class="hljs-number"><span class="hljs-number">50</span></span>), <span class="hljs-number"><span class="hljs-number">0</span></span>, <span class="hljs-number"><span class="hljs-number">0</span></span>, <span class="hljs-number"><span class="hljs-number">0</span></span>); acPolyline.AddVertexAt(<span class="hljs-number"><span class="hljs-number">3</span></span>, <span class="hljs-built_in"><span class="hljs-built_in">new</span></span> Point2d(<span class="hljs-number"><span class="hljs-number">25</span></span>, <span class="hljs-number"><span class="hljs-number">200</span></span>), <span class="hljs-number"><span class="hljs-number">0</span></span>, <span class="hljs-number"><span class="hljs-number">0</span></span>, <span class="hljs-number"><span class="hljs-number">0</span></span>); acPolyline.AddVertexAt(<span class="hljs-number"><span class="hljs-number">4</span></span>, <span class="hljs-built_in"><span class="hljs-built_in">new</span></span> Point2d(<span class="hljs-number"><span class="hljs-number">275</span></span>, <span class="hljs-number"><span class="hljs-number">200</span></span>), <span class="hljs-number"><span class="hljs-number">0</span></span>, <span class="hljs-number"><span class="hljs-number">0</span></span>, <span class="hljs-number"><span class="hljs-number">0</span></span>); acPolyline.AddVertexAt(<span class="hljs-number"><span class="hljs-number">5</span></span>, <span class="hljs-built_in"><span class="hljs-built_in">new</span></span> Point2d(<span class="hljs-number"><span class="hljs-number">50</span></span>, <span class="hljs-number"><span class="hljs-number">50</span></span>), <span class="hljs-number"><span class="hljs-number">0</span></span>, <span class="hljs-number"><span class="hljs-number">0</span></span>, <span class="hljs-number"><span class="hljs-number">0</span></span>); acBlkTblRec.AppendEntity(acPolyline); acTrans.AddNewlyCreatedDBObject(acPolyline, <span class="hljs-keyword"><span class="hljs-keyword">true</span></span>); //   -  ObjectIdCollection acObjIdColl_OUTER = <span class="hljs-built_in"><span class="hljs-built_in">new</span></span> ObjectIdCollection(); acObjIdColl_OUTER.<span class="hljs-keyword"><span class="hljs-keyword">Add</span></span>(acPolyline.ObjectId); //    <span class="hljs-type"><span class="hljs-type">Circle</span></span> acCircleOut = <span class="hljs-built_in"><span class="hljs-built_in">new</span></span> Circle(); acCircleOut.SetDatabaseDefaults(); acCircleOut.Center = <span class="hljs-built_in"><span class="hljs-built_in">new</span></span> Point3d(<span class="hljs-number"><span class="hljs-number">150</span></span>, <span class="hljs-number"><span class="hljs-number">165</span></span>, <span class="hljs-number"><span class="hljs-number">0</span></span>); acCircleOut.Radius = <span class="hljs-number"><span class="hljs-number">25</span></span>; acBlkTblRec.AppendEntity(acCircleOut); acTrans.AddNewlyCreatedDBObject(acCircleOut, <span class="hljs-keyword"><span class="hljs-keyword">true</span></span>); //   -  ObjectIdCollection acObjIdColl_INNER = <span class="hljs-built_in"><span class="hljs-built_in">new</span></span> ObjectIdCollection(); acObjIdColl_INNER.<span class="hljs-keyword"><span class="hljs-keyword">Add</span></span>(acCircleOut.ObjectId); //   Hatch acHatch = <span class="hljs-built_in"><span class="hljs-built_in">new</span></span> Hatch(); acBlkTblRec.AppendEntity(acHatch); acTrans.AddNewlyCreatedDBObject(acHatch, <span class="hljs-keyword"><span class="hljs-keyword">true</span></span>); //    acHatch.SetDatabaseDefaults(); acHatch.SetHatchPattern(HatchPatternType.PreDefined, "SOLID"); acHatch.Color = Autodesk.AutoCAD.Colors.Color.FromRgb(<span class="hljs-number"><span class="hljs-number">200</span></span>, <span class="hljs-number"><span class="hljs-number">0</span></span>, <span class="hljs-number"><span class="hljs-number">0</span></span>); acHatch.Associative = <span class="hljs-keyword"><span class="hljs-keyword">false</span></span>; acHatch.HatchStyle = HatchStyle.Normal; //     acHatch.AppendLoop(HatchLoopTypes.Outermost, acObjIdColl_OUTER); //     acHatch.AppendLoop(HatchLoopTypes.<span class="hljs-keyword"><span class="hljs-keyword">Default</span></span>, acObjIdColl_INNER); acHatch.EvaluateHatch(<span class="hljs-keyword"><span class="hljs-keyword">true</span></span>); //   acTrans.<span class="hljs-keyword"><span class="hljs-keyword">Commit</span></span>(); } }</code> </pre></div></div></div></div><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Now all parameters of the created hatching are defined. </font><font style="vertical-align: inherit;">In order for the hatching to be displayed on the screen, AutoCAD must perform the necessary calculations. </font><font style="vertical-align: inherit;">To perform these calculations, you must call the function </font></font><code>EvaluateHatch()</code><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">. </font></font><br><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">All actions needed to create hatching are performed. </font><font style="vertical-align: inherit;">We have already added it to the drawing and to the transaction in step 6. Now it remains to fix the transaction so that AutoCAD saves the changes we made.</font></font><br><br><div class="spoiler"> <b class="spoiler_title"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Finally - another note about the circle.</font></font></b> <div class="spoiler_text"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Sometimes even a programmer has to work with a drawing right in AutoCAD (in one of the following articles I wanted to talk about dynamic blocks ‚Äî this is especially true there). </font><font style="vertical-align: inherit;">In this case, to create a circle, the easiest way is to use the </font></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">DONUT</font></font></b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> command </font><font style="vertical-align: inherit;">in the AutoCAD console. </font><font style="vertical-align: inherit;">Its syntax is:</font></font><br><br><pre> <code class="hljs xml">DONUT <span class="hljs-tag"><span class="hljs-tag">&lt;</span><span class="hljs-name"><span class="hljs-tag"><span class="hljs-name"></span></span></span><span class="hljs-tag"> &gt;</span></span> <span class="hljs-tag"><span class="hljs-tag">&lt;</span><span class="hljs-name"><span class="hljs-tag"><span class="hljs-name"></span></span></span><span class="hljs-tag"> &gt;</span></span> <span class="hljs-tag"><span class="hljs-tag">&lt;</span><span class="hljs-name"><span class="hljs-tag"><span class="hljs-name"></span></span></span><span class="hljs-tag">&gt;</span></span></code> </pre><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Here are two </font></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">DONUT commands</font></font></b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> and the result of their execution:</font></font><br><br><pre> <code class="hljs nginx"><span class="hljs-attribute"><span class="hljs-attribute">DONUT</span></span> <span class="hljs-number"><span class="hljs-number">0</span></span> <span class="hljs-number"><span class="hljs-number">25</span></span> <span class="hljs-number"><span class="hljs-number">50</span></span>,<span class="hljs-number"><span class="hljs-number">50</span></span> DONUT <span class="hljs-number"><span class="hljs-number">25</span></span> <span class="hljs-number"><span class="hljs-number">75</span></span> <span class="hljs-number"><span class="hljs-number">200</span></span>,<span class="hljs-number"><span class="hljs-number">50</span></span></code> </pre><br><img src="https://habrastorage.org/files/e87/388/c98/e87388c98409433897f92759da0178a1.png"><br><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> By the way, which circle is bigger - black or white?) </font></font><br></div></div><br><h1>  PS </h1><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">The article was quite simple - but, I hope, everything is clear and accessible. </font><font style="vertical-align: inherit;">The AutoCAD .NET API allows you to draw more complex shapes, such as arcs and splines, but I haven‚Äôt been able to work with them. </font><font style="vertical-align: inherit;">Information about this, if necessary, can be found in the </font></font><a href="http://docs.autodesk.com/MAP/2014/ENU/index.html%3Furl%3DfilesACD/GUID-DE29EA57-7E55-4AC0-B3B3-68749CA0DC0C.htm,topicNumber%3DACDd30e705300"><u><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">documentation</font></font></u></a><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> ( </font></font><a href="https://sites.google.com/site/bushmansnetlaboratory/translate-manual/sozdanie-i-redaktirovanie-obektov-autocad/sozdanie-obektov"><u><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">translation</font></font></u></a><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> ). </font></font><br><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Actually, I was planning to tell here about adding text and creating simple blocks, but something already came along pretty well. </font><font style="vertical-align: inherit;">So these questions will be covered in the next article.</font></font><br><br>  Thanks for attention! <br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> Any feedback, comments and suggestions are welcome in the comments.) </font></font></div><p>Source: <a href="https://habr.com/ru/post/257129/">https://habr.com/ru/post/257129/</a></p>
<section class="more-articles-navigation-panel js-more-articles-navigation-panel">
<h4>More articles:</h4>
<nav class="list-of-articles-container js-list-of-articles-container"><ul class="list-of-pages js-list-of-pages">
<li><a href="../257119/index.html">Lectures of the Technosphere. Semester 2 Modern methods and tools for building information retrieval systems</a></li>
<li><a href="../257121/index.html">Image and video analysis. Image segmentation</a></li>
<li><a href="../257123/index.html">Develop a simple game in the game maker. Episode 1</a></li>
<li><a href="../257125/index.html">How to earn points without even starting the game</a></li>
<li><a href="../257127/index.html">Microsoft showed Project Astoria: what it will look like using Android code in Windows applications</a></li>
<li><a href="../257131/index.html">WS2812B protocol on STM32 without empty loops and interrupts. And how to make the right rainbow</a></li>
<li><a href="../257133/index.html">Beeline automatically adds a Mail.Ru search toolbar.</a></li>
<li><a href="../257135/index.html">Transhumanism to the masses: unlocking the device on Android Lollipop with an implanted NFC chip</a></li>
<li><a href="../257137/index.html">Regular passwords lit up on TV. Now the British Railways</a></li>
<li><a href="../257139/index.html">Mesosphere opens test access to its OS for data centers</a></li>
</ul></nav>
</section><br />
<a href="../../allArticles.html"><strong>All Articles</strong></a>
<script src="../../js/main.js"></script>

<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
  (function (d, w, c) {
      (w[c] = w[c] || []).push(function() {
          try {
              w.yaCounter52496797 = new Ya.Metrika({
                  id:52496797,
                  clickmap:true,
                  trackLinks:true,
                  accurateTrackBounce:true,
                  webvisor:true
              });
          } catch(e) { }
      });

      var n = d.getElementsByTagName("script")[0],
          s = d.createElement("script"),
          f = function () { n.parentNode.insertBefore(s, n); };
      s.type = "text/javascript";
      s.async = true;
      s.src = "https://mc.yandex.ru/metrika/watch.js";

      if (w.opera == "[object Opera]") {
          d.addEventListener("DOMContentLoaded", f, false);
      } else { f(); }
  })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/52496797" style="position:absolute; left:-9999px;" alt="" /></div></noscript>

<!-- Google Analytics -->
  <script>
    window.ga = function () { ga.q.push(arguments) }; ga.q = []; ga.l = +new Date;
    ga('create', 'UA-134931760-1', 'auto'); ga('send', 'pageview')
  </script>
  <script src="https://www.google-analytics.com/analytics.js" async defer></script>

</section>

  <footer class="page-footer">
    <div class="page-footer-legal-info-container page-footer-element">
      <p>
        Weekly-Geekly | <span class="page-footer-legal-info-year js-page-footer-legal-info-year">2019</span>
      </p>
    </div>
    <div class="page-footer-counters-container page-footer-element">
      <a class="page-footer-counter-clustrmap" href='#'  title='Visit tracker'><img src='https://clustrmaps.com/map_v2.png?cl=698e5a&w=271&t=t&d=6iCFw7uJz0zcOaoxz5k5PcLCJUzv2WG8G5V8M3U6Rc4&co=3a3a3a&ct=ffffff'/></a>
    </div>
  </footer>
</body>

</html>